openapi: 3.0.1
info:
  contact:
    email: info@finverse.com
    name: Maintainers
  description: Documentation of the early finverse services
  license:
    name: unknown license
  termsOfService: https://example.com
  title: Finverse Public
  version: 0.0.1
servers:
- url: https://api.prod.finverse.net/
security:
- Oauth2:
  - test
tags:
- description: Operations does not required an access token
  name: public
- description: Operations required a customer access token
  name: customer
- description: Operations required a login identity access token
  name: login_identity
- description: Operations required a link token
  name: link
paths:
  /jwks:
    get:
      description: get jwks
      operationId: getCredSubmitJwks
      security: []
      tags:
      - public
  /auth/customer/token:
    post:
      description: generate an access_token
      operationId: generateCustomerAccessToken
      security: []
      tags:
      - public
  /accounts/{accountId}:
    get:
      description: Get a specific account's information
      operationId: getAccount
      security:
      - Oauth2:
        - account
      tags:
      - login_identity
  /accounts:
    get:
      description: Get a list of accounts for a login identity
      operationId: listAccounts
      security:
      - Oauth2:
        - account
      tags:
      - login_identity
  /card_details:
    get:
      description: Get a list of card details for a login identity
      operationId: listCardDetails
      security:
      - Oauth2:
        - card:get
      tags:
      - login_identity
  /account_numbers/{accountId}:
    get:
      description: Get the account number for a specific account
      operationId: getAccountNumber
      security:
      - Oauth2:
        - account_number
      tags:
      - login_identity
  /balance_history/{accountId}:
    get:
      description: Get the balance history for a specific account
      operationId: getBalanceHistory
      security:
      - Oauth2:
        - balance_history
      tags:
      - login_identity
  /transactions/{accountId}:
    get:
      description: "Get a list of transactions for a particular account. The transactions\
        \ are returned in sorted order, with the most recent one appearing first."
      operationId: listTransactionsByAccountId
      security:
      - Oauth2:
        - transaction
      tags:
      - login_identity
  /transactions:
    get:
      description: "Get a list of transactions for a login identity. The transactions\
        \ are returned in sorted order, with the most recent one appearing first."
      operationId: listTransactionsByLoginIdentityId
      security:
      - Oauth2:
        - transaction
      tags:
      - login_identity
  /income:
    get:
      description: Get income figures for a login identity
      operationId: getIncomeEstimateByLoginIdentityId
      security:
      - Oauth2:
        - income:get
      tags:
      - login_identity
  /institutions/{institutionId}:
    get:
      description: Get a specific institution by institutionId
      operationId: getInstitution
      security:
      - Oauth2:
        - institution
      tags:
      - customer
  /institutions:
    get:
      description: Get a list of institutions
      operationId: listInstitutions
      security:
      - Oauth2:
        - institution
      tags:
      - customer
  /institutions/customer:
    get:
      description: Get a customer-specific list of institutions for Finverse Link
      operationId: getInstitutionsForCustomer
      security:
      - Oauth2:
        - institution:link
  /identity:
    get:
      description: "\\[BETA] Get a list of identity data for a given login identity"
      operationId: getIdentity
      security:
      - Oauth2:
        - identity
      tags:
      - login_identity
  /payment_links/confirm:
    post:
      description: Confirm a payment against a payment Link
      operationId: confirmPayment
      security:
      - Oauth2:
        - payment:confirm
  /payment_links/mandates:
    post:
      description: CREATE Mandate for payment link
      operationId: createPaymentLinkMandate
      security:
      - Oauth2:
        - paymentlink:mandate:create
  /payment_links/card:
    post:
      description: Initiate Card Payment for a Payment Link
      operationId: createPaymentLinkCardPayment
      security:
      - Oauth2:
        - paymentlink:cc:create
  /payment_links/fps/token:
    post:
      description: Create token for fps flow
      operationId: createFpsToken
      security:
      - Oauth2:
        - paymentlink:fps:token
  /payment_links:
    post:
      description: Create payment link
      operationId: CreatePaymentLink
      security:
      - Oauth2:
        - paymentlink:create
  /payment_links/{paymentLinkId}:
    get:
      description: Get payment link
      operationId: GetPaymentLink
      security:
      - Oauth2:
        - paymentlink:get
  /payment_links/{paymentLinkId}/cancel:
    post:
      description: Cancel a payment link
      operationId: CancelPaymentLink
      security:
      - Oauth2:
        - paymentlink:cancel
  /link:
    post:
      description: Create a new link and submit credentials
      operationId: createLink
      security:
      - Oauth2:
        - linkApi:create
      tags:
      - link
  /link/woauth:
    post:
      description: Creates a new link
      operationId: createLinkWoauth
      security:
      - Oauth2:
        - link
      tags:
      - link
  /link/token:
    post:
      description: generate a link token that can be used to create link
      operationId: generateLinkToken
      security:
      - Oauth2:
        - link:token
      tags:
      - customer
      - login_identity
  /link/relink:
    post:
      description: Update an existing link
      operationId: relink
      security:
      - Oauth2:
        - loginIdentity:update
      tags:
      - link
  /link/relink/{loginIdentityId}:
    post:
      description: Create a new link using an existing LIID
      operationId: relinkV2
      security:
      - Oauth2:
        - relinkApi:create
      tags:
      - link
  /link/action/{loginIdentityId}:
    post:
      description: Post the user action value
      operationId: linkAction
      security:
      - Oauth2:
        - linkApi:update
      tags:
      - link
  /link/status/{loginIdentityId}:
    get:
      description: Check the status of a given loginIdentity
      operationId: linkStatus
      security:
      - Oauth2:
        - linkApi:read
      tags:
      - link
  /link/fvlink/status/{loginIdentityId}:
    get:
      description: Check the status of a given login identity via FVLink
      operationId: linkStatusNonSensitive
      security:
      - Oauth2:
        - fvLinkStatus:read
      tags:
      - link
  /auth/callback:
    get:
      description: Callback url to get the oauth authorization token
      operationId: authCallback
      security: []
      tags:
      - public
  /auth/token:
    post:
      description: Exchange authorization code for token
      operationId: token
      security:
      - Oauth2:
        - loginIdentity:token
      tags:
      - link
  /auth/token/refresh:
    post:
      description: Refresh an access token
      operationId: refreshToken
      security:
      - Oauth2:
        - loginIdentity:token
      tags:
      - customer
  /login_identity/{loginIdentityId}:
    get:
      description: Get a specific loginIdentity
      operationId: getLoginIdentityById
      security:
      - Oauth2:
        - loginIdentity:get
      tags:
      - customer
  /login_identity/{loginIdentityId}/history:
    get:
      description: Get a history of events for a specific loginIdentity
      operationId: getLoginIdentityHistory
      security:
      - Oauth2:
        - loginIdentity:get
      tags:
      - customer
  /login_identity:
    delete:
      description: Delete a specific loginIdentity
      operationId: deleteLoginIdentity
      security:
      - Oauth2:
        - loginIdentity:delete
      tags:
      - login_identity
    get:
      description: Get a specific loginIdentity
      operationId: getLoginIdentity
      security:
      - Oauth2:
        - loginIdentity:self
      tags:
      - login_identity
  /login_identity/refresh:
    post:
      description: Create a refresh job for a login identity
      operationId: refreshLoginIdentity
      security:
      - Oauth2:
        - loginIdentity:update
      tags:
      - login_identity
  /statements:
    get:
      description: Get list of available statements
      operationId: getStatements
      security:
      - Oauth2:
        - statement:read
      tags:
      - login_identity
  /statements/{statementId}:
    get:
      description: Download statement
      operationId: getStatement
      security:
      - Oauth2:
        - statement:read
      tags:
      - login_identity
  /composite_statement:
    get:
      description: Download composite statement
      operationId: getCompositeStatement
      security:
      - Oauth2:
        - composite_statement
      tags:
      - login_identity
  /payments/jwks:
    get:
      description: get payment jwks
      operationId: getPaymentsJwks
      security: []
      tags:
      - public
  /payment_users/{paymentUserId}/payment_methods:
    get:
      description: List Payment Methods for a User
      operationId: listPaymentMethods
      security:
      - Oauth2:
        - payment_method:list
    post:
      description: Create a Payment Method for a user
      operationId: createPaymentMethod
      security:
      - Oauth2:
        - paymentMethod:create
  /mandates:
    get:
      description: List mandates
      operationId: listMandates
      security:
      - Oauth2:
        - mandate:list
    post:
      description: CREATE Mandate
      operationId: createMandate
      security:
      - Oauth2:
        - mandate:create
      tags:
      - customer
  /mandates/details:
    get:
      description: List mandates details
      operationId: listDetokenizedMandates
      security:
      - Oauth2:
        - mandate:listSensitive
  /mandates/institution_selection:
    post:
      description: Update InstitutionID and SenderType for Mandate
      operationId: setMandateInstitution
      security:
      - Oauth2:
        - mandate_auth:update
      tags:
      - customer
  /mandates/{mandateId}:
    get:
      description: Get Mandate details by mandate_id
      operationId: getMandate
      security:
      - Oauth2:
        - mandate:get
      tags:
      - customer
  /mandates/link:
    post:
      description: Get link to launch FV Link UI in mandate authorization mode
      operationId: getMandateAuthLink
      security:
      - Oauth2:
        - mandate:create
      tags:
      - customer
  /mandates/sender_account:
    post:
      description: Create mandate for an existing sender account
      operationId: createMandateForExistingSender
      security:
      - Oauth2:
        - mandate:create
  /payments:
    get:
      description: List Payments
      operationId: listPayments
      security:
      - Oauth2:
        - payment:list
    post:
      description: Create new Payment
      operationId: createPayment
      security:
      - Oauth2:
        - payment:create
      tags:
      - customer
  /payments/{paymentId}:
    get:
      description: Get Payment details by payment_id
      operationId: getPayment
      security:
      - Oauth2:
        - payment:get
      tags:
      - customer
    post:
      description: Update payment
      operationId: updatePayment
      security:
      - Oauth2:
        - payment:update
      tags:
      - customer
  /mandates/auth:
    get:
      description: Get Mandate Authorization by mandate id
      operationId: getMandateAuth
      security:
      - Oauth2:
        - mandate_auth:get
      tags:
      - customer
    post:
      description: Submit authorization checklist items
      operationId: submitAuthChecklist
      security:
      - Oauth2:
        - mandate_auth:update
      tags:
      - customer
  /mandates/{mandateId}/authorize:
    post:
      description: Allows a customer to authorize a specific mandate
      operationId: authorizeMandate
      security:
      - Oauth2:
        - mandates:authorize
      tags:
      - customer
  /payments/instruction:
    post:
      description: Create a new payment instruction to be used when linking to perform
        new payment
      operationId: createPaymentInstruction
      security:
      - Oauth2:
        - payment:create
      tags:
      - customer
  /testing/payments/{paymentId}/status:
    post:
      description: Update the status of a test manual payment
      operationId: updateTestPaymentStatus
      security:
      - Oauth2:
        - testPayment:update
      tags:
      - customer
  /payments/instruction/{paymentInstructionId}:
    get:
      description: Get payment instructions by payment_instruction_id
      operationId: getPaymentInstruction
      security:
      - Oauth2:
        - payment:get
      tags:
      - customer
  /payments/manual_payment:
    post:
      description: Submit manual payment confirmation
      operationId: confirmManualPayment
      security:
      - Oauth2:
        - manual_payment:confirm
  /payouts/scheduled:
    post:
      description: Create a scheduled payout
      operationId: createScheduledPayout
      security:
      - Oauth2:
        - payout:create
  /payouts/{payoutId}:
    get:
      description: Get payout by payout_id
      operationId: getPayoutById
      security:
      - Oauth2:
        - payout:get
  /payouts:
    get:
      description: List payouts
      operationId: listPayouts
      security:
      - Oauth2:
        - payout:list
  /payouts/{payoutId}/cancel:
    post:
      description: Cancel Payout by payout_id
      operationId: cancelPayout
      security:
      - Oauth2:
        - payout:cancel
  /payment_links/fps/qr_code:
    get:
      description: Get the FPS QR code
      operationId: getFpsQrCode
      security:
      - Oauth2:
        - qr_code:get
  /calculate/line_items/{paymentType}:
    get:
      description: Get line items for display
      operationId: getLineItemsForDisplay
      security:
      - Oauth2:
        - line_items:get
      tags:
      - customer
  /payment_users/{paymentUserId}/payment_accounts:
    get:
      description: Get payment account by user id
      operationId: listPaymentAccounts
      security:
      - Oauth2:
        - payment_account:get
      tags:
      - customer
  /payment_accounts:
    get:
      description: Get payment account for customer app
      operationId: listPaymentAccountsWithEnrichedData
      security:
      - Oauth2:
        - paymentAccount:list
      tags:
      - customer
    post:
      description: create payment account
      operationId: createPaymentAccount
      security:
      - Oauth2:
        - payment_account:create
      tags:
      - customer
  /payment_accounts/{paymentAccountId}:
    delete:
      description: delete payment account
      operationId: deletePaymentAccount
      security:
      - Oauth2:
        - payment_account:delete
      tags:
      - customer
  /payment_users:
    post:
      description: Create a payment user
      operationId: createPaymentUser
      security:
      - Oauth2:
        - payment_user:create
      tags:
      - customer
  /payment_users/{paymentUserId}:
    get:
      description: Get a payment user
      operationId: getPaymentUser
      security:
      - Oauth2:
        - payment_user:get
      tags:
      - customer
    post:
      description: Update a payment user
      operationId: updatePaymentUser
      security:
      - Oauth2:
        - paymentUser:update
  /payment_methods/{paymentMethodId}:
    get:
      description: Get a payment method
      operationId: getPaymentMethod
      security:
      - Oauth2:
        - paymentMethod:get
  /payment_link/fvlink/payment_user/sender:
    get:
      description: Get sender payment user in payment link flow
      operationId: getSenderPaymentUser
      security:
      - Oauth2:
        - payment_links:payment_user:get
  /payment_link/fvlink/payment_user/autopay:
    post:
      description: Set autopay consent for payment user
      operationId: setAutopayConsent
      security:
      - Oauth2:
        - paymentLink:paymentUser:setAutopayConsent
  /payment_link/fvlink/payment_method:
    get:
      description: Get payment method in payment link flow
      operationId: getPaymentMethodPaymentLink
      security:
      - Oauth2:
        - payment_links:payment_method:get
  /payment_link/fvlink/payment_method/change:
    post:
      description: Initiate change payment method from payment link front-end
      operationId: changePaymentMethodPaymentLink
      security:
      - Oauth2:
        - payment_links:payment_method:update
  /payment_link/fvlink/payment_attempt/refresh:
    post:
      description: Refresh payment attempt from payment link front-end
      operationId: refreshPaymentAttempt
      security:
      - Oauth2:
        - payment_attempt:refresh
  /payment_link/fvlink/payment:
    get:
      description: Get payment (if exists) on the payment link for front-end
      operationId: getPaymentPaymentLink
      security:
      - Oauth2:
        - paymentLinks:payment:get
  /payment_link/fvlink/payment_attempt/demote:
    post:
      description: Demote payment attempt
      operationId: demotePaymentAttempt
      security:
      - Oauth2:
        - paymentLinks:paymentAttempt:demote
  /ledger/statement:
    get:
      description: Download the balance statement for the ledger (CSV)
      operationId: downloadBalanceStatement
      security:
      - Oauth2:
        - ledger:statement
  /disputes:
    get:
      description: List Disputes
      operationId: listDisputes
      security:
      - Oauth2:
        - dispute:list
components:
  securitySchemes:
    Oauth2:
      flows:
        clientCredentials:
          scopes:
            test: Test
            account: Account
            balance: Balance
            transaction: Transaction
            credit: Credit
            investment: Investment
            institution: Institution
            link: Link
          tokenUrl: https://finverse-dev.us.auth0.com/oauth/token
      type: oauth2
x-original-swagger-version: "2.0"
