openapi: 3.0.1
info:
  contact:
    email: info@finverse.com
    name: Maintainers
  description: Documentation of the early finverse services
  license:
    name: unknown license
  termsOfService: https://example.com
  title: Finverse Public
  version: 0.0.1
servers:
- url: https://api.sandbox.finverse.net/
security:
- Oauth2:
  - test
tags:
- description: Operations does not required an access token
  name: public
- description: Operations required a customer access token
  name: customer
- description: Operations required a login identity access token
  name: login_identity
- description: Operations required a link token
  name: link
paths:
  /auth/customer/token:
    post:
      description: generate an access_token
      operationId: generateCustomerAccessToken
      tags:
      - public
  /accounts/{accountId}:
    get:
      description: Get a specific account's information
      operationId: getAccount
      security:
      - Oauth2:
        - account
      tags:
      - login_identity
  /accounts:
    get:
      description: Get a list of accounts for a login identity
      operationId: listAccounts
      security:
      - Oauth2:
        - account
      tags:
      - login_identity
  /account_numbers/{accountId}:
    get:
      description: Get the account number for a specific account
      operationId: getAccountNumber
      security:
      - Oauth2:
        - account_number
      tags:
      - login_identity
  /balance_history/{accountId}:
    get:
      description: Get the balance history for a specific account
      operationId: getBalanceHistory
      security:
      - Oauth2:
        - balance_history
      tags:
      - login_identity
  /transactions/{accountId}:
    get:
      description: Get a list of transactions for a particular account. The transactions
        are returned in sorted order, with the most recent one appearing first.
      operationId: listTransactionsByAccountId
      security:
      - Oauth2:
        - transaction
      tags:
      - login_identity
  /transactions:
    get:
      description: Get a list of transactions for a login identity. The transactions
        are returned in sorted order, with the most recent one appearing first.
      operationId: listTransactionsByLoginIdentityId
      security:
      - Oauth2:
        - transaction
      tags:
      - login_identity
  /income:
    get:
      description: Get income figures for a login identity
      operationId: getIncomeEstimateByLoginIdentityId
      security:
      - Oauth2:
        - income:get
      tags:
      - login_identity
  /institutions/{institutionId}:
    get:
      description: Get a specific institution by institutionId
      operationId: getInstitution
      security:
      - Oauth2:
        - institution
      tags:
      - customer
  /institutions:
    get:
      description: Get a list of institutions
      operationId: listInstitutions
      security:
      - Oauth2:
        - institution
      tags:
      - customer
      - link
  /identity:
    get:
      description: \[BETA] Get a list of identity data for a given login identity
      operationId: getIdentity
      security:
      - Oauth2:
        - identity
      tags:
      - login_identity
  /link:
    post:
      description: Create a new link and submit credentials
      operationId: createLink
      security:
      - Oauth2:
        - linkApi:create
      tags:
      - link
  /link/woauth:
    post:
      description: Creates a new link
      operationId: createLinkWoauth
      security:
      - Oauth2:
        - link
      tags:
      - link
  /link/token:
    post:
      description: generate a link token that can be used to create link
      operationId: generateLinkToken
      security:
      - Oauth2:
        - link:token
      tags:
      - customer
      - login_identity
  /link/relink:
    post:
      description: Update an existing link
      operationId: relink
      security:
      - Oauth2:
        - loginIdentity:update
      tags:
      - link
  /link/relink/{loginIdentityId}:
    post:
      description: Create a new link using an existing LIID
      operationId: relinkV2
      security:
      - Oauth2:
        - relinkApi:create
      tags:
      - link
  /link/action/{loginIdentityId}:
    post:
      description: Post the user action value
      operationId: linkAction
      security:
      - Oauth2:
        - linkApi:update
      tags:
      - link
  /link/status/{loginIdentityId}:
    get:
      description: Check the status of a given loginIdentity
      operationId: linkStatus
      security:
      - Oauth2:
        - linkApi:read
      tags:
      - link
  /auth/callback:
    get:
      description: Callback url to get the oauth authorization token
      operationId: authCallback
      tags:
      - public
  /auth/token:
    post:
      description: Exchange authorization code for token
      operationId: token
      security:
      - Oauth2:
        - loginIdentity:token
      tags:
      - link
  /auth/token/refresh:
    post:
      description: Refresh an access token
      operationId: refreshToken
      security:
      - Oauth2:
        - loginIdentity:token
      tags:
      - customer
  /login_identity/{loginIdentityId}:
    get:
      description: Get a specific loginIdentity
      operationId: getLoginIdentityById
      security:
      - Oauth2:
        - loginIdentity:get
      tags:
      - customer
  /login_identity/{loginIdentityId}/history:
    get:
      description: Get a history of events for a specific loginIdentity
      operationId: getLoginIdentityHistory
      security:
      - Oauth2:
        - loginIdentity:get
      tags:
      - customer
  /login_identity:
    delete:
      description: Delete a specific loginIdentity
      operationId: deleteLoginIdentity
      security:
      - Oauth2:
        - loginIdentity:delete
      tags:
      - login_identity
    get:
      description: Get a specific loginIdentity
      operationId: getLoginIdentity
      security:
      - Oauth2:
        - loginIdentity:self
      tags:
      - login_identity
  /login_identity/refresh:
    post:
      description: Create a refresh job for a login identity
      operationId: refreshLoginIdentity
      security:
      - Oauth2:
        - loginIdentity:update
      tags:
      - login_identity
  /statements:
    get:
      description: Get list of available statements
      operationId: getStatements
      security:
      - Oauth2:
        - statement:read
      tags:
      - login_identity
  /statements/{statementId}:
    get:
      description: Download statement
      operationId: getStatement
      security:
      - Oauth2:
        - statement:read
      tags:
      - login_identity
  /composite_statement:
    get:
      description: Download composite statement
      operationId: getCompositeStatement
      security:
      - Oauth2:
        - composite_statement
      tags:
      - login_identity
components:
  securitySchemes:
    Oauth2:
      flows:
        clientCredentials:
          scopes:
            test: Test
            account: Account
            balance: Balance
            transaction: Transaction
            credit: Credit
            investment: Investment
            institution: Institution
            link: Link
          tokenUrl: https://finverse-dev.us.auth0.com/oauth/token
      type: oauth2
x-original-swagger-version: "2.0"
