openapi: 3.0.1
info:
  contact:
    email: info@finverse.com
    name: Maintainers
  description: Documentation of the early finverse services
  license:
    name: unknown license
  termsOfService: https://example.com
  title: Finverse Public
  version: 0.0.1
servers:
- url: https://api.prod.finverse.net/
security:
- Oauth2:
  - test
tags:
- description: Publicly accessible endpoints
  name: public
- description: Customer endpoints
  name: customer
- description: Login identity endpoints
  name: login_identity
- description: Link endpoints
  name: link
- description: Payment endpoints
  name: payment
paths:
  /jwks:
    get:
      description: get jwks
      operationId: getCredSubmitJwks
      security: []
      tags:
      - public
  /auth/customer/token:
    post:
      description: generate an access_token
      operationId: generateCustomerAccessToken
      security: []
      tags:
      - public
  /accounts/{accountId}:
    get:
      description: Get a specific account's information
      operationId: getAccount
      security:
      - Oauth2:
        - account
      tags:
      - login_identity
  /accounts:
    get:
      description: Get a list of accounts for a login identity
      operationId: listAccounts
      security:
      - Oauth2:
        - account
      tags:
      - login_identity
  /card_details:
    get:
      description: Get a list of card details for a login identity
      operationId: listCardDetails
      security:
      - Oauth2:
        - card:get
      tags:
      - login_identity
  /account_numbers/{accountId}:
    get:
      description: Get the account number for a specific account
      operationId: getAccountNumber
      security:
      - Oauth2:
        - account_number
      tags:
      - login_identity
  /balance_history/{accountId}:
    get:
      description: Get the balance history for a specific account
      operationId: getBalanceHistory
      security:
      - Oauth2:
        - balance_history
      tags:
      - login_identity
  /transactions/{accountId}:
    get:
      description: "Get a list of transactions for a particular account. The transactions\
        \ are returned in sorted order, with the most recent one appearing first."
      operationId: listTransactionsByAccountId
      security:
      - Oauth2:
        - transaction
      tags:
      - login_identity
  /transactions:
    get:
      description: "Get a list of transactions for a login identity. The transactions\
        \ are returned in sorted order, with the most recent one appearing first."
      operationId: listTransactionsByLoginIdentityId
      security:
      - Oauth2:
        - transaction
      tags:
      - login_identity
  /income:
    get:
      description: Get income figures for a login identity
      operationId: getIncomeEstimateByLoginIdentityId
      security:
      - Oauth2:
        - income:get
      tags:
      - login_identity
  /institutions/{institutionId}:
    get:
      description: Get a specific institution by institutionId
      operationId: getInstitution
      security:
      - Oauth2:
        - institution
      tags:
      - customer
  /institutions:
    get:
      description: Get a list of institutions
      operationId: listInstitutions
      security:
      - Oauth2:
        - institution
      tags:
      - customer
  /institutions/customer:
    get:
      description: Get a customer-specific list of institutions for Finverse Link
      operationId: getInstitutionsForCustomer
      security:
      - Oauth2:
        - institution:link
      tags:
      - customer
  /identity:
    get:
      description: "\\[BETA] Get a list of identity data for a given login identity"
      operationId: getIdentity
      security:
      - Oauth2:
        - identity
      tags:
      - login_identity
  /payment_links:
    post:
      description: Create payment link
      operationId: CreatePaymentLink
      security:
      - Oauth2:
        - paymentlink:create
      tags:
      - payment
  /payment_links/{paymentLinkId}:
    get:
      description: Get payment link
      operationId: GetPaymentLink
      security:
      - Oauth2:
        - paymentlink:get
      tags:
      - payment
  /payment_links/{paymentLinkId}/cancel:
    post:
      description: Cancel a payment link
      operationId: CancelPaymentLink
      security:
      - Oauth2:
        - paymentlink:cancel
      tags:
      - payment
  /payment_links/kcp/payment:
    post:
      description: Complete a KCP payment
      operationId: completeKcpPayment
      security:
      - Oauth2:
        - kcp:completePayment
      tags:
      - payment
  /link:
    post:
      description: Create a new link and submit credentials
      operationId: createLink
      security:
      - Oauth2:
        - linkApi:create
      tags:
      - link
  /link/token:
    post:
      description: generate a link token that can be used to create link
      operationId: generateLinkToken
      security:
      - Oauth2:
        - link:token
      tags:
      - link
  /link/relink/{loginIdentityId}:
    post:
      description: Create a new link using an existing LIID
      operationId: relinkV2
      security:
      - Oauth2:
        - relinkApi:create
      tags:
      - link
  /link/action/{loginIdentityId}:
    post:
      description: Post the user action value
      operationId: linkAction
      security:
      - Oauth2:
        - linkApi:update
      tags:
      - link
  /link/status/{loginIdentityId}:
    get:
      description: Check the status of a given loginIdentity
      operationId: linkStatus
      security:
      - Oauth2:
        - linkApi:read
      tags:
      - link
  /auth/token:
    post:
      description: Exchange authorization code for token
      operationId: token
      security:
      - Oauth2:
        - loginIdentity:token
      tags:
      - link
  /auth/token/refresh:
    post:
      description: Refresh an access token
      operationId: refreshToken
      security:
      - Oauth2:
        - loginIdentity:token
      tags:
      - customer
  /login_identity/{loginIdentityId}:
    get:
      description: Get a specific loginIdentity
      operationId: getLoginIdentityById
      security:
      - Oauth2:
        - loginIdentity:get
      tags:
      - login_identity
  /login_identity/{loginIdentityId}/history:
    get:
      description: Get a history of events for a specific loginIdentity
      operationId: getLoginIdentityHistory
      security:
      - Oauth2:
        - loginIdentity:get
      tags:
      - login_identity
  /login_identity:
    delete:
      description: Delete a specific loginIdentity
      operationId: deleteLoginIdentity
      security:
      - Oauth2:
        - loginIdentity:delete
      tags:
      - login_identity
    get:
      description: Get a specific loginIdentity
      operationId: getLoginIdentity
      security:
      - Oauth2:
        - loginIdentity:self
      tags:
      - login_identity
  /login_identity/refresh:
    post:
      description: Create a refresh job for a login identity
      operationId: refreshLoginIdentity
      security:
      - Oauth2:
        - loginIdentity:update
      tags:
      - login_identity
  /statements:
    get:
      description: Get list of available statements
      operationId: getStatements
      security:
      - Oauth2:
        - statement:read
      tags:
      - login_identity
  /statements/{statementId}:
    get:
      description: Download statement
      operationId: getStatement
      security:
      - Oauth2:
        - statement:read
      tags:
      - login_identity
  /composite_statement:
    get:
      description: Download composite statement
      operationId: getCompositeStatement
      security:
      - Oauth2:
        - composite_statement
      tags:
      - login_identity
  /payments/jwks:
    get:
      description: get payment jwks
      operationId: getPaymentsJwks
      security: []
      tags:
      - public
  /payment_users/{paymentUserId}/payment_methods:
    get:
      description: List Payment Methods for a User
      operationId: listPaymentMethods
      security:
      - Oauth2:
        - payment_method:list
      tags:
      - payment
    post:
      description: Create a Payment Method for a user
      operationId: createPaymentMethod
      security:
      - Oauth2:
        - paymentMethod:create
      tags:
      - payment
  /mandates:
    get:
      description: List mandates
      operationId: listMandates
      security:
      - Oauth2:
        - mandate:list
      tags:
      - payment
    post:
      description: CREATE Mandate
      operationId: createMandate
      security:
      - Oauth2:
        - mandate:create
      tags:
      - payment
  /mandates/details:
    get:
      description: List mandates details
      operationId: listDetokenizedMandates
      security:
      - Oauth2:
        - mandate:listSensitive
      tags:
      - payment
  /mandates/institution_selection:
    post:
      description: Update InstitutionID and SenderType for Mandate
      operationId: setMandateInstitution
      security:
      - Oauth2:
        - mandate_auth:update
      tags:
      - payment
  /mandates/{mandateId}:
    get:
      description: Get Mandate details by mandate_id
      operationId: getMandate
      security:
      - Oauth2:
        - mandate:get
      tags:
      - payment
  /mandates/link:
    post:
      description: Get link to launch FV Link UI in mandate authorization mode
      operationId: getMandateAuthLink
      security:
      - Oauth2:
        - mandate:create
      tags:
      - payment
  /mandates/sender_account:
    post:
      description: Create mandate for an existing sender account
      operationId: createMandateForExistingSender
      security:
      - Oauth2:
        - mandate:create
      tags:
      - payment
  /payments:
    get:
      description: List Payments
      operationId: listPayments
      security:
      - Oauth2:
        - payment:list
      tags:
      - payment
    post:
      description: Create new Payment
      operationId: createPayment
      security:
      - Oauth2:
        - payment:create
      tags:
      - payment
  /payments/{paymentId}:
    get:
      description: Get Payment details by payment_id
      operationId: getPayment
      security:
      - Oauth2:
        - payment:get
      tags:
      - payment
    post:
      description: Update payment
      operationId: updatePayment
      security:
      - Oauth2:
        - payment:update
      tags:
      - payment
  /mandates/auth:
    get:
      description: Get Mandate Authorization by mandate id
      operationId: getMandateAuth
      security:
      - Oauth2:
        - mandate_auth:get
      tags:
      - payment
    post:
      description: Submit authorization checklist items
      operationId: submitAuthChecklist
      security:
      - Oauth2:
        - mandate_auth:update
      tags:
      - payment
  /mandates/{mandateId}/authorize:
    post:
      description: Allows a customer to authorize a specific mandate
      operationId: authorizeMandate
      security:
      - Oauth2:
        - mandates:authorize
      tags:
      - payment
  /testing/payments/{paymentId}/status:
    post:
      deprecated: true
      description: "[DEPRECATED] Update the status of a test manual payment"
      operationId: updateTestPaymentStatus
      security:
      - Oauth2:
        - testPayment:update
      tags:
      - payment
  /payouts/{payoutId}:
    get:
      description: Get payout by payout_id
      operationId: getPayoutById
      security:
      - Oauth2:
        - payout:get
      tags:
      - payment
  /payouts:
    get:
      description: List payouts
      operationId: listPayouts
      security:
      - Oauth2:
        - payout:list
      tags:
      - payment
    post:
      description: Create a payout
      operationId: createPayout
      security:
      - Oauth2:
        - payout:create
      tags:
      - payment
  /payouts/{payoutId}/confirm:
    post:
      description: "Confirm a payout that was created with confirm = false, submitting\
        \ it for processing"
      operationId: confirmPayout
      security:
      - Oauth2:
        - payout:confirm
      tags:
      - payment
  /payouts/{payoutId}/cancel:
    post:
      description: Cancel Payout by payout_id
      operationId: cancelPayout
      security:
      - Oauth2:
        - payout:cancel
      tags:
      - payment
  /payment_users/{paymentUserId}/payment_accounts:
    get:
      description: Get payment account by user id
      operationId: listPaymentAccounts
      security:
      - Oauth2:
        - payment_account:get
      tags:
      - payment
  /payment_accounts:
    get:
      description: Get payment account for customer app
      operationId: listPaymentAccountsWithEnrichedData
      security:
      - Oauth2:
        - paymentAccount:list
      tags:
      - payment
    post:
      description: create payment account
      operationId: createPaymentAccount
      security:
      - Oauth2:
        - payment_account:create
      tags:
      - payment
  /payment_accounts/{paymentAccountId}:
    delete:
      description: delete payment account
      operationId: deletePaymentAccount
      security:
      - Oauth2:
        - payment_account:delete
      tags:
      - payment
  /payment_users:
    post:
      description: Create a payment user
      operationId: createPaymentUser
      security:
      - Oauth2:
        - payment_user:create
      tags:
      - payment
  /payment_users/{paymentUserId}:
    get:
      description: Get a payment user
      operationId: getPaymentUser
      security:
      - Oauth2:
        - payment_user:get
      tags:
      - payment
    post:
      description: Update a payment user
      operationId: updatePaymentUser
      security:
      - Oauth2:
        - paymentUser:update
      tags:
      - payment
  /payment_methods/{paymentMethodId}:
    get:
      description: Get a payment method
      operationId: getPaymentMethod
      security:
      - Oauth2:
        - paymentMethod:get
      tags:
      - payment
  /payment_methods/{paymentMethodId}/cancel:
    post:
      description: Cancel a payment method
      operationId: cancelPaymentMethod
      security:
      - Oauth2:
        - paymentMethod:cancel
      tags:
      - payment
  /ledger/statement:
    get:
      description: Download the balance statement for the ledger (CSV)
      operationId: downloadBalanceStatement
      security:
      - Oauth2:
        - ledger:statement
      tags:
      - payment
  /disputes:
    get:
      description: List Disputes
      operationId: listDisputes
      security:
      - Oauth2:
        - dispute:list
      tags:
      - payment
  /bills/{billId}:
    get:
      description: Get a bill by ID
      operationId: getBill
      security:
      - Oauth2:
        - bill:get
      tags:
      - payment
  /bills:
    get:
      description: List bills
      operationId: listBills
      security:
      - Oauth2:
        - bill:list
      tags:
      - payment
  /payment_link/fvlink/adyen/payment_methods:
    get:
      description: Get available Adyen payment methods for Advanced card setup (proxy
        to Adyen /paymentMethods)
      operationId: getAdyenCardSetupPaymentMethods
      security:
      - Oauth2:
        - adyenCheckout:bootstrap
      tags:
      - payment
  /payment_link/fvlink/adyen/payments:
    post:
      description: Submit Adyen card setup payment (proxy to Adyen /payments with
        Drop-in state.data from onSubmit)
      operationId: submitAdyenCardSetupPayment
      security:
      - Oauth2:
        - adyenCheckout:submit
      tags:
      - payment
  /payment_link/fvlink/adyen/payments/details:
    post:
      description: Submit Adyen card setup payment details (proxy to Adyen /payments/details
        with Drop-in state.data from onAdditionalDetails)
      operationId: submitAdyenCardSetupPaymentDetails
      security:
      - Oauth2:
        - adyenCheckout:submit
      tags:
      - payment
components:
  securitySchemes:
    Oauth2:
      flows:
        clientCredentials:
          scopes:
            test: Test
            account: Account
            balance: Balance
            transaction: Transaction
            credit: Credit
            investment: Investment
            institution: Institution
            link: Link
          tokenUrl: https://finverse-dev.us.auth0.com/oauth/token
      type: oauth2
x-original-swagger-version: "2.0"
