/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// CreateFpsTokenRequest struct for CreateFpsTokenRequest
type CreateFpsTokenRequest struct {
	InvoiceId string `json:"invoice_id"`
}

// NewCreateFpsTokenRequest instantiates a new CreateFpsTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFpsTokenRequest(invoiceId string) *CreateFpsTokenRequest {
	this := CreateFpsTokenRequest{}
	this.InvoiceId = invoiceId
	return &this
}

// NewCreateFpsTokenRequestWithDefaults instantiates a new CreateFpsTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFpsTokenRequestWithDefaults() *CreateFpsTokenRequest {
	this := CreateFpsTokenRequest{}
	return &this
}

// GetInvoiceId returns the InvoiceId field value
func (o *CreateFpsTokenRequest) GetInvoiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvoiceId
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value
// and a boolean to check if the value has been set.
func (o *CreateFpsTokenRequest) GetInvoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceId, true
}

// SetInvoiceId sets field value
func (o *CreateFpsTokenRequest) SetInvoiceId(v string) {
	o.InvoiceId = v
}

func (o CreateFpsTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["invoice_id"] = o.InvoiceId
	}
	return json.Marshal(toSerialize)
}

type NullableCreateFpsTokenRequest struct {
	value *CreateFpsTokenRequest
	isSet bool
}

func (v NullableCreateFpsTokenRequest) Get() *CreateFpsTokenRequest {
	return v.value
}

func (v *NullableCreateFpsTokenRequest) Set(val *CreateFpsTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFpsTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFpsTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFpsTokenRequest(val *CreateFpsTokenRequest) *NullableCreateFpsTokenRequest {
	return &NullableCreateFpsTokenRequest{value: val, isSet: true}
}

func (v NullableCreateFpsTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFpsTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
