/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// SenderAccountFvLinkResponse struct for SenderAccountFvLinkResponse
type SenderAccountFvLinkResponse struct {
	AccountNumberMasked *string `json:"account_number_masked,omitempty"`
	InstitutionId       *string `json:"institution_id,omitempty"`
	InstitutionName     *string `json:"institution_name,omitempty"`
}

// NewSenderAccountFvLinkResponse instantiates a new SenderAccountFvLinkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSenderAccountFvLinkResponse() *SenderAccountFvLinkResponse {
	this := SenderAccountFvLinkResponse{}
	return &this
}

// NewSenderAccountFvLinkResponseWithDefaults instantiates a new SenderAccountFvLinkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSenderAccountFvLinkResponseWithDefaults() *SenderAccountFvLinkResponse {
	this := SenderAccountFvLinkResponse{}
	return &this
}

// GetAccountNumberMasked returns the AccountNumberMasked field value if set, zero value otherwise.
func (o *SenderAccountFvLinkResponse) GetAccountNumberMasked() string {
	if o == nil || o.AccountNumberMasked == nil {
		var ret string
		return ret
	}
	return *o.AccountNumberMasked
}

// GetAccountNumberMaskedOk returns a tuple with the AccountNumberMasked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderAccountFvLinkResponse) GetAccountNumberMaskedOk() (*string, bool) {
	if o == nil || o.AccountNumberMasked == nil {
		return nil, false
	}
	return o.AccountNumberMasked, true
}

// HasAccountNumberMasked returns a boolean if a field has been set.
func (o *SenderAccountFvLinkResponse) HasAccountNumberMasked() bool {
	if o != nil && o.AccountNumberMasked != nil {
		return true
	}

	return false
}

// SetAccountNumberMasked gets a reference to the given string and assigns it to the AccountNumberMasked field.
func (o *SenderAccountFvLinkResponse) SetAccountNumberMasked(v string) {
	o.AccountNumberMasked = &v
}

// GetInstitutionId returns the InstitutionId field value if set, zero value otherwise.
func (o *SenderAccountFvLinkResponse) GetInstitutionId() string {
	if o == nil || o.InstitutionId == nil {
		var ret string
		return ret
	}
	return *o.InstitutionId
}

// GetInstitutionIdOk returns a tuple with the InstitutionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderAccountFvLinkResponse) GetInstitutionIdOk() (*string, bool) {
	if o == nil || o.InstitutionId == nil {
		return nil, false
	}
	return o.InstitutionId, true
}

// HasInstitutionId returns a boolean if a field has been set.
func (o *SenderAccountFvLinkResponse) HasInstitutionId() bool {
	if o != nil && o.InstitutionId != nil {
		return true
	}

	return false
}

// SetInstitutionId gets a reference to the given string and assigns it to the InstitutionId field.
func (o *SenderAccountFvLinkResponse) SetInstitutionId(v string) {
	o.InstitutionId = &v
}

// GetInstitutionName returns the InstitutionName field value if set, zero value otherwise.
func (o *SenderAccountFvLinkResponse) GetInstitutionName() string {
	if o == nil || o.InstitutionName == nil {
		var ret string
		return ret
	}
	return *o.InstitutionName
}

// GetInstitutionNameOk returns a tuple with the InstitutionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderAccountFvLinkResponse) GetInstitutionNameOk() (*string, bool) {
	if o == nil || o.InstitutionName == nil {
		return nil, false
	}
	return o.InstitutionName, true
}

// HasInstitutionName returns a boolean if a field has been set.
func (o *SenderAccountFvLinkResponse) HasInstitutionName() bool {
	if o != nil && o.InstitutionName != nil {
		return true
	}

	return false
}

// SetInstitutionName gets a reference to the given string and assigns it to the InstitutionName field.
func (o *SenderAccountFvLinkResponse) SetInstitutionName(v string) {
	o.InstitutionName = &v
}

func (o SenderAccountFvLinkResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountNumberMasked != nil {
		toSerialize["account_number_masked"] = o.AccountNumberMasked
	}
	if o.InstitutionId != nil {
		toSerialize["institution_id"] = o.InstitutionId
	}
	if o.InstitutionName != nil {
		toSerialize["institution_name"] = o.InstitutionName
	}
	return json.Marshal(toSerialize)
}

type NullableSenderAccountFvLinkResponse struct {
	value *SenderAccountFvLinkResponse
	isSet bool
}

func (v NullableSenderAccountFvLinkResponse) Get() *SenderAccountFvLinkResponse {
	return v.value
}

func (v *NullableSenderAccountFvLinkResponse) Set(val *SenderAccountFvLinkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSenderAccountFvLinkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSenderAccountFvLinkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSenderAccountFvLinkResponse(val *SenderAccountFvLinkResponse) *NullableSenderAccountFvLinkResponse {
	return &NullableSenderAccountFvLinkResponse{value: val, isSet: true}
}

func (v NullableSenderAccountFvLinkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSenderAccountFvLinkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
