/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// PaymentSnapshotPaymentMethod struct for PaymentSnapshotPaymentMethod
type PaymentSnapshotPaymentMethod struct {
	Card *PaymentSnapshotPaymentMethodCard `json:"card,omitempty"`
}

// NewPaymentSnapshotPaymentMethod instantiates a new PaymentSnapshotPaymentMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentSnapshotPaymentMethod() *PaymentSnapshotPaymentMethod {
	this := PaymentSnapshotPaymentMethod{}
	return &this
}

// NewPaymentSnapshotPaymentMethodWithDefaults instantiates a new PaymentSnapshotPaymentMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentSnapshotPaymentMethodWithDefaults() *PaymentSnapshotPaymentMethod {
	this := PaymentSnapshotPaymentMethod{}
	return &this
}

// GetCard returns the Card field value if set, zero value otherwise.
func (o *PaymentSnapshotPaymentMethod) GetCard() PaymentSnapshotPaymentMethodCard {
	if o == nil || o.Card == nil {
		var ret PaymentSnapshotPaymentMethodCard
		return ret
	}
	return *o.Card
}

// GetCardOk returns a tuple with the Card field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSnapshotPaymentMethod) GetCardOk() (*PaymentSnapshotPaymentMethodCard, bool) {
	if o == nil || o.Card == nil {
		return nil, false
	}
	return o.Card, true
}

// HasCard returns a boolean if a field has been set.
func (o *PaymentSnapshotPaymentMethod) HasCard() bool {
	if o != nil && o.Card != nil {
		return true
	}

	return false
}

// SetCard gets a reference to the given PaymentSnapshotPaymentMethodCard and assigns it to the Card field.
func (o *PaymentSnapshotPaymentMethod) SetCard(v PaymentSnapshotPaymentMethodCard) {
	o.Card = &v
}

func (o PaymentSnapshotPaymentMethod) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Card != nil {
		toSerialize["card"] = o.Card
	}
	return json.Marshal(toSerialize)
}

type NullablePaymentSnapshotPaymentMethod struct {
	value *PaymentSnapshotPaymentMethod
	isSet bool
}

func (v NullablePaymentSnapshotPaymentMethod) Get() *PaymentSnapshotPaymentMethod {
	return v.value
}

func (v *NullablePaymentSnapshotPaymentMethod) Set(val *PaymentSnapshotPaymentMethod) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentSnapshotPaymentMethod) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentSnapshotPaymentMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentSnapshotPaymentMethod(val *PaymentSnapshotPaymentMethod) *NullablePaymentSnapshotPaymentMethod {
	return &NullablePaymentSnapshotPaymentMethod{value: val, isSet: true}
}

func (v NullablePaymentSnapshotPaymentMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentSnapshotPaymentMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
