/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// checks if the GetAccountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccountResponse{}

// GetAccountResponse struct for GetAccountResponse
type GetAccountResponse struct {
	Account       *Account            `json:"account,omitempty"`
	LoginIdentity *LoginIdentityShort `json:"login_identity,omitempty"`
	Institution   *InstitutionShort   `json:"institution,omitempty"`
}

// NewGetAccountResponse instantiates a new GetAccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountResponse() *GetAccountResponse {
	this := GetAccountResponse{}
	return &this
}

// NewGetAccountResponseWithDefaults instantiates a new GetAccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountResponseWithDefaults() *GetAccountResponse {
	this := GetAccountResponse{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *GetAccountResponse) GetAccount() Account {
	if o == nil || IsNil(o.Account) {
		var ret Account
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetAccountOk() (*Account, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *GetAccountResponse) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given Account and assigns it to the Account field.
func (o *GetAccountResponse) SetAccount(v Account) {
	o.Account = &v
}

// GetLoginIdentity returns the LoginIdentity field value if set, zero value otherwise.
func (o *GetAccountResponse) GetLoginIdentity() LoginIdentityShort {
	if o == nil || IsNil(o.LoginIdentity) {
		var ret LoginIdentityShort
		return ret
	}
	return *o.LoginIdentity
}

// GetLoginIdentityOk returns a tuple with the LoginIdentity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetLoginIdentityOk() (*LoginIdentityShort, bool) {
	if o == nil || IsNil(o.LoginIdentity) {
		return nil, false
	}
	return o.LoginIdentity, true
}

// HasLoginIdentity returns a boolean if a field has been set.
func (o *GetAccountResponse) HasLoginIdentity() bool {
	if o != nil && !IsNil(o.LoginIdentity) {
		return true
	}

	return false
}

// SetLoginIdentity gets a reference to the given LoginIdentityShort and assigns it to the LoginIdentity field.
func (o *GetAccountResponse) SetLoginIdentity(v LoginIdentityShort) {
	o.LoginIdentity = &v
}

// GetInstitution returns the Institution field value if set, zero value otherwise.
func (o *GetAccountResponse) GetInstitution() InstitutionShort {
	if o == nil || IsNil(o.Institution) {
		var ret InstitutionShort
		return ret
	}
	return *o.Institution
}

// GetInstitutionOk returns a tuple with the Institution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountResponse) GetInstitutionOk() (*InstitutionShort, bool) {
	if o == nil || IsNil(o.Institution) {
		return nil, false
	}
	return o.Institution, true
}

// HasInstitution returns a boolean if a field has been set.
func (o *GetAccountResponse) HasInstitution() bool {
	if o != nil && !IsNil(o.Institution) {
		return true
	}

	return false
}

// SetInstitution gets a reference to the given InstitutionShort and assigns it to the Institution field.
func (o *GetAccountResponse) SetInstitution(v InstitutionShort) {
	o.Institution = &v
}

func (o GetAccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAccountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.LoginIdentity) {
		toSerialize["login_identity"] = o.LoginIdentity
	}
	if !IsNil(o.Institution) {
		toSerialize["institution"] = o.Institution
	}
	return toSerialize, nil
}

type NullableGetAccountResponse struct {
	value *GetAccountResponse
	isSet bool
}

func (v NullableGetAccountResponse) Get() *GetAccountResponse {
	return v.value
}

func (v *NullableGetAccountResponse) Set(val *GetAccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountResponse(val *GetAccountResponse) *NullableGetAccountResponse {
	return &NullableGetAccountResponse{value: val, isSet: true}
}

func (v NullableGetAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
