/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// checks if the PaymentLinkConfigs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentLinkConfigs{}

// PaymentLinkConfigs struct for PaymentLinkConfigs
type PaymentLinkConfigs struct {
	DisplayConfigs       *DisplayConfigs `json:"display_configs,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaymentLinkConfigs PaymentLinkConfigs

// NewPaymentLinkConfigs instantiates a new PaymentLinkConfigs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentLinkConfigs() *PaymentLinkConfigs {
	this := PaymentLinkConfigs{}
	return &this
}

// NewPaymentLinkConfigsWithDefaults instantiates a new PaymentLinkConfigs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentLinkConfigsWithDefaults() *PaymentLinkConfigs {
	this := PaymentLinkConfigs{}
	return &this
}

// GetDisplayConfigs returns the DisplayConfigs field value if set, zero value otherwise.
func (o *PaymentLinkConfigs) GetDisplayConfigs() DisplayConfigs {
	if o == nil || IsNil(o.DisplayConfigs) {
		var ret DisplayConfigs
		return ret
	}
	return *o.DisplayConfigs
}

// GetDisplayConfigsOk returns a tuple with the DisplayConfigs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkConfigs) GetDisplayConfigsOk() (*DisplayConfigs, bool) {
	if o == nil || IsNil(o.DisplayConfigs) {
		return nil, false
	}
	return o.DisplayConfigs, true
}

// HasDisplayConfigs returns a boolean if a field has been set.
func (o *PaymentLinkConfigs) HasDisplayConfigs() bool {
	if o != nil && !IsNil(o.DisplayConfigs) {
		return true
	}

	return false
}

// SetDisplayConfigs gets a reference to the given DisplayConfigs and assigns it to the DisplayConfigs field.
func (o *PaymentLinkConfigs) SetDisplayConfigs(v DisplayConfigs) {
	o.DisplayConfigs = &v
}

func (o PaymentLinkConfigs) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentLinkConfigs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayConfigs) {
		toSerialize["display_configs"] = o.DisplayConfigs
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentLinkConfigs) UnmarshalJSON(data []byte) (err error) {
	varPaymentLinkConfigs := _PaymentLinkConfigs{}

	err = json.Unmarshal(data, &varPaymentLinkConfigs)

	if err != nil {
		return err
	}

	*o = PaymentLinkConfigs(varPaymentLinkConfigs)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "display_configs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaymentLinkConfigs struct {
	value *PaymentLinkConfigs
	isSet bool
}

func (v NullablePaymentLinkConfigs) Get() *PaymentLinkConfigs {
	return v.value
}

func (v *NullablePaymentLinkConfigs) Set(val *PaymentLinkConfigs) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentLinkConfigs) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentLinkConfigs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentLinkConfigs(val *PaymentLinkConfigs) *NullablePaymentLinkConfigs {
	return &NullablePaymentLinkConfigs{value: val, isSet: true}
}

func (v NullablePaymentLinkConfigs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentLinkConfigs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
