/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
	"fmt"
)

// checks if the PaymentMethodFvLinkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodFvLinkResponse{}

// PaymentMethodFvLinkResponse struct for PaymentMethodFvLinkResponse
type PaymentMethodFvLinkResponse struct {
	PaymentMethodId      string                 `json:"payment_method_id"`
	PaymentMethodType    PaymentMethodType      `json:"payment_method_type"`
	RecipientEntityName  *string                `json:"recipient_entity_name,omitempty"`
	Mandate              *MandateFvLinkResponse `json:"mandate,omitempty"`
	Card                 *CardFvLinkResponse    `json:"card,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaymentMethodFvLinkResponse PaymentMethodFvLinkResponse

// NewPaymentMethodFvLinkResponse instantiates a new PaymentMethodFvLinkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentMethodFvLinkResponse(paymentMethodId string, paymentMethodType PaymentMethodType) *PaymentMethodFvLinkResponse {
	this := PaymentMethodFvLinkResponse{}
	this.PaymentMethodId = paymentMethodId
	this.PaymentMethodType = paymentMethodType
	return &this
}

// NewPaymentMethodFvLinkResponseWithDefaults instantiates a new PaymentMethodFvLinkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentMethodFvLinkResponseWithDefaults() *PaymentMethodFvLinkResponse {
	this := PaymentMethodFvLinkResponse{}
	return &this
}

// GetPaymentMethodId returns the PaymentMethodId field value
func (o *PaymentMethodFvLinkResponse) GetPaymentMethodId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentMethodId
}

// GetPaymentMethodIdOk returns a tuple with the PaymentMethodId field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodFvLinkResponse) GetPaymentMethodIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethodId, true
}

// SetPaymentMethodId sets field value
func (o *PaymentMethodFvLinkResponse) SetPaymentMethodId(v string) {
	o.PaymentMethodId = v
}

// GetPaymentMethodType returns the PaymentMethodType field value
func (o *PaymentMethodFvLinkResponse) GetPaymentMethodType() PaymentMethodType {
	if o == nil {
		var ret PaymentMethodType
		return ret
	}

	return o.PaymentMethodType
}

// GetPaymentMethodTypeOk returns a tuple with the PaymentMethodType field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodFvLinkResponse) GetPaymentMethodTypeOk() (*PaymentMethodType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethodType, true
}

// SetPaymentMethodType sets field value
func (o *PaymentMethodFvLinkResponse) SetPaymentMethodType(v PaymentMethodType) {
	o.PaymentMethodType = v
}

// GetRecipientEntityName returns the RecipientEntityName field value if set, zero value otherwise.
func (o *PaymentMethodFvLinkResponse) GetRecipientEntityName() string {
	if o == nil || IsNil(o.RecipientEntityName) {
		var ret string
		return ret
	}
	return *o.RecipientEntityName
}

// GetRecipientEntityNameOk returns a tuple with the RecipientEntityName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodFvLinkResponse) GetRecipientEntityNameOk() (*string, bool) {
	if o == nil || IsNil(o.RecipientEntityName) {
		return nil, false
	}
	return o.RecipientEntityName, true
}

// HasRecipientEntityName returns a boolean if a field has been set.
func (o *PaymentMethodFvLinkResponse) HasRecipientEntityName() bool {
	if o != nil && !IsNil(o.RecipientEntityName) {
		return true
	}

	return false
}

// SetRecipientEntityName gets a reference to the given string and assigns it to the RecipientEntityName field.
func (o *PaymentMethodFvLinkResponse) SetRecipientEntityName(v string) {
	o.RecipientEntityName = &v
}

// GetMandate returns the Mandate field value if set, zero value otherwise.
func (o *PaymentMethodFvLinkResponse) GetMandate() MandateFvLinkResponse {
	if o == nil || IsNil(o.Mandate) {
		var ret MandateFvLinkResponse
		return ret
	}
	return *o.Mandate
}

// GetMandateOk returns a tuple with the Mandate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodFvLinkResponse) GetMandateOk() (*MandateFvLinkResponse, bool) {
	if o == nil || IsNil(o.Mandate) {
		return nil, false
	}
	return o.Mandate, true
}

// HasMandate returns a boolean if a field has been set.
func (o *PaymentMethodFvLinkResponse) HasMandate() bool {
	if o != nil && !IsNil(o.Mandate) {
		return true
	}

	return false
}

// SetMandate gets a reference to the given MandateFvLinkResponse and assigns it to the Mandate field.
func (o *PaymentMethodFvLinkResponse) SetMandate(v MandateFvLinkResponse) {
	o.Mandate = &v
}

// GetCard returns the Card field value if set, zero value otherwise.
func (o *PaymentMethodFvLinkResponse) GetCard() CardFvLinkResponse {
	if o == nil || IsNil(o.Card) {
		var ret CardFvLinkResponse
		return ret
	}
	return *o.Card
}

// GetCardOk returns a tuple with the Card field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodFvLinkResponse) GetCardOk() (*CardFvLinkResponse, bool) {
	if o == nil || IsNil(o.Card) {
		return nil, false
	}
	return o.Card, true
}

// HasCard returns a boolean if a field has been set.
func (o *PaymentMethodFvLinkResponse) HasCard() bool {
	if o != nil && !IsNil(o.Card) {
		return true
	}

	return false
}

// SetCard gets a reference to the given CardFvLinkResponse and assigns it to the Card field.
func (o *PaymentMethodFvLinkResponse) SetCard(v CardFvLinkResponse) {
	o.Card = &v
}

func (o PaymentMethodFvLinkResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodFvLinkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["payment_method_id"] = o.PaymentMethodId
	toSerialize["payment_method_type"] = o.PaymentMethodType
	if !IsNil(o.RecipientEntityName) {
		toSerialize["recipient_entity_name"] = o.RecipientEntityName
	}
	if !IsNil(o.Mandate) {
		toSerialize["mandate"] = o.Mandate
	}
	if !IsNil(o.Card) {
		toSerialize["card"] = o.Card
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentMethodFvLinkResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"payment_method_id",
		"payment_method_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentMethodFvLinkResponse := _PaymentMethodFvLinkResponse{}

	err = json.Unmarshal(data, &varPaymentMethodFvLinkResponse)

	if err != nil {
		return err
	}

	*o = PaymentMethodFvLinkResponse(varPaymentMethodFvLinkResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "payment_method_id")
		delete(additionalProperties, "payment_method_type")
		delete(additionalProperties, "recipient_entity_name")
		delete(additionalProperties, "mandate")
		delete(additionalProperties, "card")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaymentMethodFvLinkResponse struct {
	value *PaymentMethodFvLinkResponse
	isSet bool
}

func (v NullablePaymentMethodFvLinkResponse) Get() *PaymentMethodFvLinkResponse {
	return v.value
}

func (v *NullablePaymentMethodFvLinkResponse) Set(val *PaymentMethodFvLinkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethodFvLinkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethodFvLinkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethodFvLinkResponse(val *PaymentMethodFvLinkResponse) *NullablePaymentMethodFvLinkResponse {
	return &NullablePaymentMethodFvLinkResponse{value: val, isSet: true}
}

func (v NullablePaymentMethodFvLinkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethodFvLinkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
