/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
	"time"
)

// GetMandateAuthResponse struct for GetMandateAuthResponse
type GetMandateAuthResponse struct {
	// Finverse Mandate ID
	MandateId string `json:"mandate_id"`
	// Mandate status
	MandateStatus string `json:"mandate_status"`
	// Merchant account ID assigned by Finverse
	RecipientAccountId string `json:"recipient_account_id"`
	// Finverse Institution ID. Only returned if institution_id was included in the request.
	InstitutionId string `json:"institution_id"`
	// Type of account held by the Sender at the Institution. Possible values are INDIVIDUAL, BUSINESS
	SenderType *string `json:"sender_type,omitempty"`
	// Checklist of the authorization factors needed to complete Mandate authorization
	AuthChecklist  []AuthChecklistFactor     `json:"auth_checklist"`
	EncryptionInfo MandateAuthEncryptionInfo `json:"encryption_info"`
	// Timestamp in ISO format (YYYY-MM-DDTHH:MM:SS.SSSZ)
	LastUpdate     time.Time               `json:"last_update"`
	Error          *FvEmbeddedErrorModel   `json:"error,omitempty"`
	MandateDetails *MandateDetailsResponse `json:"mandate_details,omitempty"`
	Recipient      *MandateRecipient       `json:"recipient,omitempty"`
}

// NewGetMandateAuthResponse instantiates a new GetMandateAuthResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMandateAuthResponse(mandateId string, mandateStatus string, recipientAccountId string, institutionId string, authChecklist []AuthChecklistFactor, encryptionInfo MandateAuthEncryptionInfo, lastUpdate time.Time) *GetMandateAuthResponse {
	this := GetMandateAuthResponse{}
	this.MandateId = mandateId
	this.MandateStatus = mandateStatus
	this.RecipientAccountId = recipientAccountId
	this.InstitutionId = institutionId
	this.AuthChecklist = authChecklist
	this.EncryptionInfo = encryptionInfo
	this.LastUpdate = lastUpdate
	return &this
}

// NewGetMandateAuthResponseWithDefaults instantiates a new GetMandateAuthResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMandateAuthResponseWithDefaults() *GetMandateAuthResponse {
	this := GetMandateAuthResponse{}
	return &this
}

// GetMandateId returns the MandateId field value
func (o *GetMandateAuthResponse) GetMandateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MandateId
}

// GetMandateIdOk returns a tuple with the MandateId field value
// and a boolean to check if the value has been set.
func (o *GetMandateAuthResponse) GetMandateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MandateId, true
}

// SetMandateId sets field value
func (o *GetMandateAuthResponse) SetMandateId(v string) {
	o.MandateId = v
}

// GetMandateStatus returns the MandateStatus field value
func (o *GetMandateAuthResponse) GetMandateStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MandateStatus
}

// GetMandateStatusOk returns a tuple with the MandateStatus field value
// and a boolean to check if the value has been set.
func (o *GetMandateAuthResponse) GetMandateStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MandateStatus, true
}

// SetMandateStatus sets field value
func (o *GetMandateAuthResponse) SetMandateStatus(v string) {
	o.MandateStatus = v
}

// GetRecipientAccountId returns the RecipientAccountId field value
func (o *GetMandateAuthResponse) GetRecipientAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecipientAccountId
}

// GetRecipientAccountIdOk returns a tuple with the RecipientAccountId field value
// and a boolean to check if the value has been set.
func (o *GetMandateAuthResponse) GetRecipientAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecipientAccountId, true
}

// SetRecipientAccountId sets field value
func (o *GetMandateAuthResponse) SetRecipientAccountId(v string) {
	o.RecipientAccountId = v
}

// GetInstitutionId returns the InstitutionId field value
func (o *GetMandateAuthResponse) GetInstitutionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstitutionId
}

// GetInstitutionIdOk returns a tuple with the InstitutionId field value
// and a boolean to check if the value has been set.
func (o *GetMandateAuthResponse) GetInstitutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstitutionId, true
}

// SetInstitutionId sets field value
func (o *GetMandateAuthResponse) SetInstitutionId(v string) {
	o.InstitutionId = v
}

// GetSenderType returns the SenderType field value if set, zero value otherwise.
func (o *GetMandateAuthResponse) GetSenderType() string {
	if o == nil || o.SenderType == nil {
		var ret string
		return ret
	}
	return *o.SenderType
}

// GetSenderTypeOk returns a tuple with the SenderType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMandateAuthResponse) GetSenderTypeOk() (*string, bool) {
	if o == nil || o.SenderType == nil {
		return nil, false
	}
	return o.SenderType, true
}

// HasSenderType returns a boolean if a field has been set.
func (o *GetMandateAuthResponse) HasSenderType() bool {
	if o != nil && o.SenderType != nil {
		return true
	}

	return false
}

// SetSenderType gets a reference to the given string and assigns it to the SenderType field.
func (o *GetMandateAuthResponse) SetSenderType(v string) {
	o.SenderType = &v
}

// GetAuthChecklist returns the AuthChecklist field value
func (o *GetMandateAuthResponse) GetAuthChecklist() []AuthChecklistFactor {
	if o == nil {
		var ret []AuthChecklistFactor
		return ret
	}

	return o.AuthChecklist
}

// GetAuthChecklistOk returns a tuple with the AuthChecklist field value
// and a boolean to check if the value has been set.
func (o *GetMandateAuthResponse) GetAuthChecklistOk() ([]AuthChecklistFactor, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthChecklist, true
}

// SetAuthChecklist sets field value
func (o *GetMandateAuthResponse) SetAuthChecklist(v []AuthChecklistFactor) {
	o.AuthChecklist = v
}

// GetEncryptionInfo returns the EncryptionInfo field value
func (o *GetMandateAuthResponse) GetEncryptionInfo() MandateAuthEncryptionInfo {
	if o == nil {
		var ret MandateAuthEncryptionInfo
		return ret
	}

	return o.EncryptionInfo
}

// GetEncryptionInfoOk returns a tuple with the EncryptionInfo field value
// and a boolean to check if the value has been set.
func (o *GetMandateAuthResponse) GetEncryptionInfoOk() (*MandateAuthEncryptionInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EncryptionInfo, true
}

// SetEncryptionInfo sets field value
func (o *GetMandateAuthResponse) SetEncryptionInfo(v MandateAuthEncryptionInfo) {
	o.EncryptionInfo = v
}

// GetLastUpdate returns the LastUpdate field value
func (o *GetMandateAuthResponse) GetLastUpdate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUpdate
}

// GetLastUpdateOk returns a tuple with the LastUpdate field value
// and a boolean to check if the value has been set.
func (o *GetMandateAuthResponse) GetLastUpdateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdate, true
}

// SetLastUpdate sets field value
func (o *GetMandateAuthResponse) SetLastUpdate(v time.Time) {
	o.LastUpdate = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetMandateAuthResponse) GetError() FvEmbeddedErrorModel {
	if o == nil || o.Error == nil {
		var ret FvEmbeddedErrorModel
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMandateAuthResponse) GetErrorOk() (*FvEmbeddedErrorModel, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetMandateAuthResponse) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given FvEmbeddedErrorModel and assigns it to the Error field.
func (o *GetMandateAuthResponse) SetError(v FvEmbeddedErrorModel) {
	o.Error = &v
}

// GetMandateDetails returns the MandateDetails field value if set, zero value otherwise.
func (o *GetMandateAuthResponse) GetMandateDetails() MandateDetailsResponse {
	if o == nil || o.MandateDetails == nil {
		var ret MandateDetailsResponse
		return ret
	}
	return *o.MandateDetails
}

// GetMandateDetailsOk returns a tuple with the MandateDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMandateAuthResponse) GetMandateDetailsOk() (*MandateDetailsResponse, bool) {
	if o == nil || o.MandateDetails == nil {
		return nil, false
	}
	return o.MandateDetails, true
}

// HasMandateDetails returns a boolean if a field has been set.
func (o *GetMandateAuthResponse) HasMandateDetails() bool {
	if o != nil && o.MandateDetails != nil {
		return true
	}

	return false
}

// SetMandateDetails gets a reference to the given MandateDetailsResponse and assigns it to the MandateDetails field.
func (o *GetMandateAuthResponse) SetMandateDetails(v MandateDetailsResponse) {
	o.MandateDetails = &v
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *GetMandateAuthResponse) GetRecipient() MandateRecipient {
	if o == nil || o.Recipient == nil {
		var ret MandateRecipient
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMandateAuthResponse) GetRecipientOk() (*MandateRecipient, bool) {
	if o == nil || o.Recipient == nil {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *GetMandateAuthResponse) HasRecipient() bool {
	if o != nil && o.Recipient != nil {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given MandateRecipient and assigns it to the Recipient field.
func (o *GetMandateAuthResponse) SetRecipient(v MandateRecipient) {
	o.Recipient = &v
}

func (o GetMandateAuthResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["mandate_id"] = o.MandateId
	}
	if true {
		toSerialize["mandate_status"] = o.MandateStatus
	}
	if true {
		toSerialize["recipient_account_id"] = o.RecipientAccountId
	}
	if true {
		toSerialize["institution_id"] = o.InstitutionId
	}
	if o.SenderType != nil {
		toSerialize["sender_type"] = o.SenderType
	}
	if true {
		toSerialize["auth_checklist"] = o.AuthChecklist
	}
	if true {
		toSerialize["encryption_info"] = o.EncryptionInfo
	}
	if true {
		toSerialize["last_update"] = o.LastUpdate
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	if o.MandateDetails != nil {
		toSerialize["mandate_details"] = o.MandateDetails
	}
	if o.Recipient != nil {
		toSerialize["recipient"] = o.Recipient
	}
	return json.Marshal(toSerialize)
}

type NullableGetMandateAuthResponse struct {
	value *GetMandateAuthResponse
	isSet bool
}

func (v NullableGetMandateAuthResponse) Get() *GetMandateAuthResponse {
	return v.value
}

func (v *NullableGetMandateAuthResponse) Set(val *GetMandateAuthResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMandateAuthResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMandateAuthResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMandateAuthResponse(val *GetMandateAuthResponse) *NullableGetMandateAuthResponse {
	return &NullableGetMandateAuthResponse{value: val, isSet: true}
}

func (v NullableGetMandateAuthResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMandateAuthResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
