/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// checks if the PaymentProcessorDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentProcessorDetails{}

// PaymentProcessorDetails struct for PaymentProcessorDetails
type PaymentProcessorDetails struct {
	AuthCode             *string                 `json:"auth_code,omitempty"`
	ProcessorId          *string                 `json:"processor_id,omitempty"`
	ProcessorReference   *string                 `json:"processor_reference,omitempty"`
	Result               *PaymentProcessorResult `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaymentProcessorDetails PaymentProcessorDetails

// NewPaymentProcessorDetails instantiates a new PaymentProcessorDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentProcessorDetails() *PaymentProcessorDetails {
	this := PaymentProcessorDetails{}
	return &this
}

// NewPaymentProcessorDetailsWithDefaults instantiates a new PaymentProcessorDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentProcessorDetailsWithDefaults() *PaymentProcessorDetails {
	this := PaymentProcessorDetails{}
	return &this
}

// GetAuthCode returns the AuthCode field value if set, zero value otherwise.
func (o *PaymentProcessorDetails) GetAuthCode() string {
	if o == nil || IsNil(o.AuthCode) {
		var ret string
		return ret
	}
	return *o.AuthCode
}

// GetAuthCodeOk returns a tuple with the AuthCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentProcessorDetails) GetAuthCodeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthCode) {
		return nil, false
	}
	return o.AuthCode, true
}

// HasAuthCode returns a boolean if a field has been set.
func (o *PaymentProcessorDetails) HasAuthCode() bool {
	if o != nil && !IsNil(o.AuthCode) {
		return true
	}

	return false
}

// SetAuthCode gets a reference to the given string and assigns it to the AuthCode field.
func (o *PaymentProcessorDetails) SetAuthCode(v string) {
	o.AuthCode = &v
}

// GetProcessorId returns the ProcessorId field value if set, zero value otherwise.
func (o *PaymentProcessorDetails) GetProcessorId() string {
	if o == nil || IsNil(o.ProcessorId) {
		var ret string
		return ret
	}
	return *o.ProcessorId
}

// GetProcessorIdOk returns a tuple with the ProcessorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentProcessorDetails) GetProcessorIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProcessorId) {
		return nil, false
	}
	return o.ProcessorId, true
}

// HasProcessorId returns a boolean if a field has been set.
func (o *PaymentProcessorDetails) HasProcessorId() bool {
	if o != nil && !IsNil(o.ProcessorId) {
		return true
	}

	return false
}

// SetProcessorId gets a reference to the given string and assigns it to the ProcessorId field.
func (o *PaymentProcessorDetails) SetProcessorId(v string) {
	o.ProcessorId = &v
}

// GetProcessorReference returns the ProcessorReference field value if set, zero value otherwise.
func (o *PaymentProcessorDetails) GetProcessorReference() string {
	if o == nil || IsNil(o.ProcessorReference) {
		var ret string
		return ret
	}
	return *o.ProcessorReference
}

// GetProcessorReferenceOk returns a tuple with the ProcessorReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentProcessorDetails) GetProcessorReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.ProcessorReference) {
		return nil, false
	}
	return o.ProcessorReference, true
}

// HasProcessorReference returns a boolean if a field has been set.
func (o *PaymentProcessorDetails) HasProcessorReference() bool {
	if o != nil && !IsNil(o.ProcessorReference) {
		return true
	}

	return false
}

// SetProcessorReference gets a reference to the given string and assigns it to the ProcessorReference field.
func (o *PaymentProcessorDetails) SetProcessorReference(v string) {
	o.ProcessorReference = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *PaymentProcessorDetails) GetResult() PaymentProcessorResult {
	if o == nil || IsNil(o.Result) {
		var ret PaymentProcessorResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentProcessorDetails) GetResultOk() (*PaymentProcessorResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *PaymentProcessorDetails) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given PaymentProcessorResult and assigns it to the Result field.
func (o *PaymentProcessorDetails) SetResult(v PaymentProcessorResult) {
	o.Result = &v
}

func (o PaymentProcessorDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentProcessorDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthCode) {
		toSerialize["auth_code"] = o.AuthCode
	}
	if !IsNil(o.ProcessorId) {
		toSerialize["processor_id"] = o.ProcessorId
	}
	if !IsNil(o.ProcessorReference) {
		toSerialize["processor_reference"] = o.ProcessorReference
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentProcessorDetails) UnmarshalJSON(data []byte) (err error) {
	varPaymentProcessorDetails := _PaymentProcessorDetails{}

	err = json.Unmarshal(data, &varPaymentProcessorDetails)

	if err != nil {
		return err
	}

	*o = PaymentProcessorDetails(varPaymentProcessorDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "auth_code")
		delete(additionalProperties, "processor_id")
		delete(additionalProperties, "processor_reference")
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaymentProcessorDetails struct {
	value *PaymentProcessorDetails
	isSet bool
}

func (v NullablePaymentProcessorDetails) Get() *PaymentProcessorDetails {
	return v.value
}

func (v *NullablePaymentProcessorDetails) Set(val *PaymentProcessorDetails) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentProcessorDetails) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentProcessorDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentProcessorDetails(val *PaymentProcessorDetails) *NullablePaymentProcessorDetails {
	return &NullablePaymentProcessorDetails{value: val, isSet: true}
}

func (v NullablePaymentProcessorDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentProcessorDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
