/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// checks if the FVWalletDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FVWalletDetails{}

// FVWalletDetails struct for FVWalletDetails
type FVWalletDetails struct {
	// The wallet brand
	Brand *string `json:"brand,omitempty"`
	// The brand product name
	BrandProductName *string `json:"brand_product_name,omitempty"`
	// The issuer country
	Country              *string `json:"country,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FVWalletDetails FVWalletDetails

// NewFVWalletDetails instantiates a new FVWalletDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFVWalletDetails() *FVWalletDetails {
	this := FVWalletDetails{}
	return &this
}

// NewFVWalletDetailsWithDefaults instantiates a new FVWalletDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFVWalletDetailsWithDefaults() *FVWalletDetails {
	this := FVWalletDetails{}
	return &this
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *FVWalletDetails) GetBrand() string {
	if o == nil || IsNil(o.Brand) {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FVWalletDetails) GetBrandOk() (*string, bool) {
	if o == nil || IsNil(o.Brand) {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *FVWalletDetails) HasBrand() bool {
	if o != nil && !IsNil(o.Brand) {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *FVWalletDetails) SetBrand(v string) {
	o.Brand = &v
}

// GetBrandProductName returns the BrandProductName field value if set, zero value otherwise.
func (o *FVWalletDetails) GetBrandProductName() string {
	if o == nil || IsNil(o.BrandProductName) {
		var ret string
		return ret
	}
	return *o.BrandProductName
}

// GetBrandProductNameOk returns a tuple with the BrandProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FVWalletDetails) GetBrandProductNameOk() (*string, bool) {
	if o == nil || IsNil(o.BrandProductName) {
		return nil, false
	}
	return o.BrandProductName, true
}

// HasBrandProductName returns a boolean if a field has been set.
func (o *FVWalletDetails) HasBrandProductName() bool {
	if o != nil && !IsNil(o.BrandProductName) {
		return true
	}

	return false
}

// SetBrandProductName gets a reference to the given string and assigns it to the BrandProductName field.
func (o *FVWalletDetails) SetBrandProductName(v string) {
	o.BrandProductName = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *FVWalletDetails) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FVWalletDetails) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *FVWalletDetails) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *FVWalletDetails) SetCountry(v string) {
	o.Country = &v
}

func (o FVWalletDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FVWalletDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Brand) {
		toSerialize["brand"] = o.Brand
	}
	if !IsNil(o.BrandProductName) {
		toSerialize["brand_product_name"] = o.BrandProductName
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FVWalletDetails) UnmarshalJSON(data []byte) (err error) {
	varFVWalletDetails := _FVWalletDetails{}

	err = json.Unmarshal(data, &varFVWalletDetails)

	if err != nil {
		return err
	}

	*o = FVWalletDetails(varFVWalletDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "brand")
		delete(additionalProperties, "brand_product_name")
		delete(additionalProperties, "country")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFVWalletDetails struct {
	value *FVWalletDetails
	isSet bool
}

func (v NullableFVWalletDetails) Get() *FVWalletDetails {
	return v.value
}

func (v *NullableFVWalletDetails) Set(val *FVWalletDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableFVWalletDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableFVWalletDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFVWalletDetails(val *FVWalletDetails) *NullableFVWalletDetails {
	return &NullableFVWalletDetails{value: val, isSet: true}
}

func (v NullableFVWalletDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFVWalletDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
