/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// ListCardsDetailsResponse struct for ListCardsDetailsResponse
type ListCardsDetailsResponse struct {
	LoginIdentity *LoginIdentityShort `json:"login_identity,omitempty"`
	Institution   *InstitutionShort   `json:"institution,omitempty"`
	CardDetails   *CardDetails        `json:"card_details,omitempty"`
}

// NewListCardsDetailsResponse instantiates a new ListCardsDetailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCardsDetailsResponse() *ListCardsDetailsResponse {
	this := ListCardsDetailsResponse{}
	return &this
}

// NewListCardsDetailsResponseWithDefaults instantiates a new ListCardsDetailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCardsDetailsResponseWithDefaults() *ListCardsDetailsResponse {
	this := ListCardsDetailsResponse{}
	return &this
}

// GetLoginIdentity returns the LoginIdentity field value if set, zero value otherwise.
func (o *ListCardsDetailsResponse) GetLoginIdentity() LoginIdentityShort {
	if o == nil || o.LoginIdentity == nil {
		var ret LoginIdentityShort
		return ret
	}
	return *o.LoginIdentity
}

// GetLoginIdentityOk returns a tuple with the LoginIdentity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCardsDetailsResponse) GetLoginIdentityOk() (*LoginIdentityShort, bool) {
	if o == nil || o.LoginIdentity == nil {
		return nil, false
	}
	return o.LoginIdentity, true
}

// HasLoginIdentity returns a boolean if a field has been set.
func (o *ListCardsDetailsResponse) HasLoginIdentity() bool {
	if o != nil && o.LoginIdentity != nil {
		return true
	}

	return false
}

// SetLoginIdentity gets a reference to the given LoginIdentityShort and assigns it to the LoginIdentity field.
func (o *ListCardsDetailsResponse) SetLoginIdentity(v LoginIdentityShort) {
	o.LoginIdentity = &v
}

// GetInstitution returns the Institution field value if set, zero value otherwise.
func (o *ListCardsDetailsResponse) GetInstitution() InstitutionShort {
	if o == nil || o.Institution == nil {
		var ret InstitutionShort
		return ret
	}
	return *o.Institution
}

// GetInstitutionOk returns a tuple with the Institution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCardsDetailsResponse) GetInstitutionOk() (*InstitutionShort, bool) {
	if o == nil || o.Institution == nil {
		return nil, false
	}
	return o.Institution, true
}

// HasInstitution returns a boolean if a field has been set.
func (o *ListCardsDetailsResponse) HasInstitution() bool {
	if o != nil && o.Institution != nil {
		return true
	}

	return false
}

// SetInstitution gets a reference to the given InstitutionShort and assigns it to the Institution field.
func (o *ListCardsDetailsResponse) SetInstitution(v InstitutionShort) {
	o.Institution = &v
}

// GetCardDetails returns the CardDetails field value if set, zero value otherwise.
func (o *ListCardsDetailsResponse) GetCardDetails() CardDetails {
	if o == nil || o.CardDetails == nil {
		var ret CardDetails
		return ret
	}
	return *o.CardDetails
}

// GetCardDetailsOk returns a tuple with the CardDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCardsDetailsResponse) GetCardDetailsOk() (*CardDetails, bool) {
	if o == nil || o.CardDetails == nil {
		return nil, false
	}
	return o.CardDetails, true
}

// HasCardDetails returns a boolean if a field has been set.
func (o *ListCardsDetailsResponse) HasCardDetails() bool {
	if o != nil && o.CardDetails != nil {
		return true
	}

	return false
}

// SetCardDetails gets a reference to the given CardDetails and assigns it to the CardDetails field.
func (o *ListCardsDetailsResponse) SetCardDetails(v CardDetails) {
	o.CardDetails = &v
}

func (o ListCardsDetailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.LoginIdentity != nil {
		toSerialize["login_identity"] = o.LoginIdentity
	}
	if o.Institution != nil {
		toSerialize["institution"] = o.Institution
	}
	if o.CardDetails != nil {
		toSerialize["card_details"] = o.CardDetails
	}
	return json.Marshal(toSerialize)
}

type NullableListCardsDetailsResponse struct {
	value *ListCardsDetailsResponse
	isSet bool
}

func (v NullableListCardsDetailsResponse) Get() *ListCardsDetailsResponse {
	return v.value
}

func (v *NullableListCardsDetailsResponse) Set(val *ListCardsDetailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListCardsDetailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListCardsDetailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCardsDetailsResponse(val *ListCardsDetailsResponse) *NullableListCardsDetailsResponse {
	return &NullableListCardsDetailsResponse{value: val, isSet: true}
}

func (v NullableListCardsDetailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCardsDetailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
