/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// PaymentLinkRecipientAccount struct for PaymentLinkRecipientAccount
type PaymentLinkRecipientAccount struct {
	// Merchant account ID assigned by Finverse
	RecipientAccountId string `json:"recipient_account_id"`
}

// NewPaymentLinkRecipientAccount instantiates a new PaymentLinkRecipientAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentLinkRecipientAccount(recipientAccountId string) *PaymentLinkRecipientAccount {
	this := PaymentLinkRecipientAccount{}
	this.RecipientAccountId = recipientAccountId
	return &this
}

// NewPaymentLinkRecipientAccountWithDefaults instantiates a new PaymentLinkRecipientAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentLinkRecipientAccountWithDefaults() *PaymentLinkRecipientAccount {
	this := PaymentLinkRecipientAccount{}
	return &this
}

// GetRecipientAccountId returns the RecipientAccountId field value
func (o *PaymentLinkRecipientAccount) GetRecipientAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecipientAccountId
}

// GetRecipientAccountIdOk returns a tuple with the RecipientAccountId field value
// and a boolean to check if the value has been set.
func (o *PaymentLinkRecipientAccount) GetRecipientAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecipientAccountId, true
}

// SetRecipientAccountId sets field value
func (o *PaymentLinkRecipientAccount) SetRecipientAccountId(v string) {
	o.RecipientAccountId = v
}

func (o PaymentLinkRecipientAccount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["recipient_account_id"] = o.RecipientAccountId
	}
	return json.Marshal(toSerialize)
}

type NullablePaymentLinkRecipientAccount struct {
	value *PaymentLinkRecipientAccount
	isSet bool
}

func (v NullablePaymentLinkRecipientAccount) Get() *PaymentLinkRecipientAccount {
	return v.value
}

func (v *NullablePaymentLinkRecipientAccount) Set(val *PaymentLinkRecipientAccount) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentLinkRecipientAccount) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentLinkRecipientAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentLinkRecipientAccount(val *PaymentLinkRecipientAccount) *NullablePaymentLinkRecipientAccount {
	return &NullablePaymentLinkRecipientAccount{value: val, isSet: true}
}

func (v NullablePaymentLinkRecipientAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentLinkRecipientAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
