/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// UserField struct for UserField
type UserField struct {
	// The name of the field. This will be used as the key when submitting response.
	Name string `json:"name"`
	// The label for this field.
	Label *string `json:"label,omitempty"`
	// The placeholder for this field.
	Placeholder *string `json:"placeholder,omitempty"`
	// The type of field. Currently it can only be SELECT, INPUT or PASSWORD
	Type string `json:"type"`
	// This is only applicable when the field type is SELECT
	Options []UserFieldOption `json:"options,omitempty"`
}

// NewUserField instantiates a new UserField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserField(name string, type_ string) *UserField {
	this := UserField{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewUserFieldWithDefaults instantiates a new UserField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserFieldWithDefaults() *UserField {
	this := UserField{}
	return &this
}

// GetName returns the Name field value
func (o *UserField) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserField) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserField) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *UserField) GetLabel() string {
	if o == nil || o.Label == nil {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserField) GetLabelOk() (*string, bool) {
	if o == nil || o.Label == nil {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *UserField) HasLabel() bool {
	if o != nil && o.Label != nil {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *UserField) SetLabel(v string) {
	o.Label = &v
}

// GetPlaceholder returns the Placeholder field value if set, zero value otherwise.
func (o *UserField) GetPlaceholder() string {
	if o == nil || o.Placeholder == nil {
		var ret string
		return ret
	}
	return *o.Placeholder
}

// GetPlaceholderOk returns a tuple with the Placeholder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserField) GetPlaceholderOk() (*string, bool) {
	if o == nil || o.Placeholder == nil {
		return nil, false
	}
	return o.Placeholder, true
}

// HasPlaceholder returns a boolean if a field has been set.
func (o *UserField) HasPlaceholder() bool {
	if o != nil && o.Placeholder != nil {
		return true
	}

	return false
}

// SetPlaceholder gets a reference to the given string and assigns it to the Placeholder field.
func (o *UserField) SetPlaceholder(v string) {
	o.Placeholder = &v
}

// GetType returns the Type field value
func (o *UserField) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UserField) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UserField) SetType(v string) {
	o.Type = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *UserField) GetOptions() []UserFieldOption {
	if o == nil || o.Options == nil {
		var ret []UserFieldOption
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserField) GetOptionsOk() ([]UserFieldOption, bool) {
	if o == nil || o.Options == nil {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *UserField) HasOptions() bool {
	if o != nil && o.Options != nil {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []UserFieldOption and assigns it to the Options field.
func (o *UserField) SetOptions(v []UserFieldOption) {
	o.Options = v
}

func (o UserField) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Label != nil {
		toSerialize["label"] = o.Label
	}
	if o.Placeholder != nil {
		toSerialize["placeholder"] = o.Placeholder
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableUserField struct {
	value *UserField
	isSet bool
}

func (v NullableUserField) Get() *UserField {
	return v.value
}

func (v *NullableUserField) Set(val *UserField) {
	v.value = val
	v.isSet = true
}

func (v NullableUserField) IsSet() bool {
	return v.isSet
}

func (v *NullableUserField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserField(val *UserField) *NullableUserField {
	return &NullableUserField{value: val, isSet: true}
}

func (v NullableUserField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
