/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// checks if the MandateDetailsForPaymentLinkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MandateDetailsForPaymentLinkRequest{}

// MandateDetailsForPaymentLinkRequest struct for MandateDetailsForPaymentLinkRequest
type MandateDetailsForPaymentLinkRequest struct {
	// YYYY-MM-DD, must be later than or the same as the date of creation. If unspecified, default to the date of creation.
	StartDate NullableString `json:"start_date,omitempty"`
	// YYYY-MM-DD, must be later than the date of creation.
	EndDate           NullableString            `json:"end_date,omitempty"`
	TransactionLimits *TransactionLimitsRequest `json:"transaction_limits,omitempty"`
	// End-user facing description of the mandate (used in notifications, and in payments if no description is provided)
	Description          *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MandateDetailsForPaymentLinkRequest MandateDetailsForPaymentLinkRequest

// NewMandateDetailsForPaymentLinkRequest instantiates a new MandateDetailsForPaymentLinkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMandateDetailsForPaymentLinkRequest() *MandateDetailsForPaymentLinkRequest {
	this := MandateDetailsForPaymentLinkRequest{}
	return &this
}

// NewMandateDetailsForPaymentLinkRequestWithDefaults instantiates a new MandateDetailsForPaymentLinkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMandateDetailsForPaymentLinkRequestWithDefaults() *MandateDetailsForPaymentLinkRequest {
	this := MandateDetailsForPaymentLinkRequest{}
	return &this
}

// GetStartDate returns the StartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MandateDetailsForPaymentLinkRequest) GetStartDate() string {
	if o == nil || IsNil(o.StartDate.Get()) {
		var ret string
		return ret
	}
	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MandateDetailsForPaymentLinkRequest) GetStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// HasStartDate returns a boolean if a field has been set.
func (o *MandateDetailsForPaymentLinkRequest) HasStartDate() bool {
	if o != nil && o.StartDate.IsSet() {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given NullableString and assigns it to the StartDate field.
func (o *MandateDetailsForPaymentLinkRequest) SetStartDate(v string) {
	o.StartDate.Set(&v)
}

// SetStartDateNil sets the value for StartDate to be an explicit nil
func (o *MandateDetailsForPaymentLinkRequest) SetStartDateNil() {
	o.StartDate.Set(nil)
}

// UnsetStartDate ensures that no value is present for StartDate, not even an explicit nil
func (o *MandateDetailsForPaymentLinkRequest) UnsetStartDate() {
	o.StartDate.Unset()
}

// GetEndDate returns the EndDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MandateDetailsForPaymentLinkRequest) GetEndDate() string {
	if o == nil || IsNil(o.EndDate.Get()) {
		var ret string
		return ret
	}
	return *o.EndDate.Get()
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MandateDetailsForPaymentLinkRequest) GetEndDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDate.Get(), o.EndDate.IsSet()
}

// HasEndDate returns a boolean if a field has been set.
func (o *MandateDetailsForPaymentLinkRequest) HasEndDate() bool {
	if o != nil && o.EndDate.IsSet() {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given NullableString and assigns it to the EndDate field.
func (o *MandateDetailsForPaymentLinkRequest) SetEndDate(v string) {
	o.EndDate.Set(&v)
}

// SetEndDateNil sets the value for EndDate to be an explicit nil
func (o *MandateDetailsForPaymentLinkRequest) SetEndDateNil() {
	o.EndDate.Set(nil)
}

// UnsetEndDate ensures that no value is present for EndDate, not even an explicit nil
func (o *MandateDetailsForPaymentLinkRequest) UnsetEndDate() {
	o.EndDate.Unset()
}

// GetTransactionLimits returns the TransactionLimits field value if set, zero value otherwise.
func (o *MandateDetailsForPaymentLinkRequest) GetTransactionLimits() TransactionLimitsRequest {
	if o == nil || IsNil(o.TransactionLimits) {
		var ret TransactionLimitsRequest
		return ret
	}
	return *o.TransactionLimits
}

// GetTransactionLimitsOk returns a tuple with the TransactionLimits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MandateDetailsForPaymentLinkRequest) GetTransactionLimitsOk() (*TransactionLimitsRequest, bool) {
	if o == nil || IsNil(o.TransactionLimits) {
		return nil, false
	}
	return o.TransactionLimits, true
}

// HasTransactionLimits returns a boolean if a field has been set.
func (o *MandateDetailsForPaymentLinkRequest) HasTransactionLimits() bool {
	if o != nil && !IsNil(o.TransactionLimits) {
		return true
	}

	return false
}

// SetTransactionLimits gets a reference to the given TransactionLimitsRequest and assigns it to the TransactionLimits field.
func (o *MandateDetailsForPaymentLinkRequest) SetTransactionLimits(v TransactionLimitsRequest) {
	o.TransactionLimits = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MandateDetailsForPaymentLinkRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MandateDetailsForPaymentLinkRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MandateDetailsForPaymentLinkRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MandateDetailsForPaymentLinkRequest) SetDescription(v string) {
	o.Description = &v
}

func (o MandateDetailsForPaymentLinkRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MandateDetailsForPaymentLinkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.StartDate.IsSet() {
		toSerialize["start_date"] = o.StartDate.Get()
	}
	if o.EndDate.IsSet() {
		toSerialize["end_date"] = o.EndDate.Get()
	}
	if !IsNil(o.TransactionLimits) {
		toSerialize["transaction_limits"] = o.TransactionLimits
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MandateDetailsForPaymentLinkRequest) UnmarshalJSON(data []byte) (err error) {
	varMandateDetailsForPaymentLinkRequest := _MandateDetailsForPaymentLinkRequest{}

	err = json.Unmarshal(data, &varMandateDetailsForPaymentLinkRequest)

	if err != nil {
		return err
	}

	*o = MandateDetailsForPaymentLinkRequest(varMandateDetailsForPaymentLinkRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "start_date")
		delete(additionalProperties, "end_date")
		delete(additionalProperties, "transaction_limits")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMandateDetailsForPaymentLinkRequest struct {
	value *MandateDetailsForPaymentLinkRequest
	isSet bool
}

func (v NullableMandateDetailsForPaymentLinkRequest) Get() *MandateDetailsForPaymentLinkRequest {
	return v.value
}

func (v *NullableMandateDetailsForPaymentLinkRequest) Set(val *MandateDetailsForPaymentLinkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMandateDetailsForPaymentLinkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMandateDetailsForPaymentLinkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMandateDetailsForPaymentLinkRequest(val *MandateDetailsForPaymentLinkRequest) *NullableMandateDetailsForPaymentLinkRequest {
	return &NullableMandateDetailsForPaymentLinkRequest{value: val, isSet: true}
}

func (v NullableMandateDetailsForPaymentLinkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMandateDetailsForPaymentLinkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
