/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// CreatePaymentMethodRequestIntegrationMetadata struct for CreatePaymentMethodRequestIntegrationMetadata
type CreatePaymentMethodRequestIntegrationMetadata struct {
	IntegrationId  string                                                      `json:"integration_id"`
	StripeMetadata CreatePaymentMethodRequestIntegrationMetadataStripeMetadata `json:"stripe_metadata"`
}

// NewCreatePaymentMethodRequestIntegrationMetadata instantiates a new CreatePaymentMethodRequestIntegrationMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePaymentMethodRequestIntegrationMetadata(integrationId string, stripeMetadata CreatePaymentMethodRequestIntegrationMetadataStripeMetadata) *CreatePaymentMethodRequestIntegrationMetadata {
	this := CreatePaymentMethodRequestIntegrationMetadata{}
	this.IntegrationId = integrationId
	this.StripeMetadata = stripeMetadata
	return &this
}

// NewCreatePaymentMethodRequestIntegrationMetadataWithDefaults instantiates a new CreatePaymentMethodRequestIntegrationMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePaymentMethodRequestIntegrationMetadataWithDefaults() *CreatePaymentMethodRequestIntegrationMetadata {
	this := CreatePaymentMethodRequestIntegrationMetadata{}
	return &this
}

// GetIntegrationId returns the IntegrationId field value
func (o *CreatePaymentMethodRequestIntegrationMetadata) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *CreatePaymentMethodRequestIntegrationMetadata) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *CreatePaymentMethodRequestIntegrationMetadata) SetIntegrationId(v string) {
	o.IntegrationId = v
}

// GetStripeMetadata returns the StripeMetadata field value
func (o *CreatePaymentMethodRequestIntegrationMetadata) GetStripeMetadata() CreatePaymentMethodRequestIntegrationMetadataStripeMetadata {
	if o == nil {
		var ret CreatePaymentMethodRequestIntegrationMetadataStripeMetadata
		return ret
	}

	return o.StripeMetadata
}

// GetStripeMetadataOk returns a tuple with the StripeMetadata field value
// and a boolean to check if the value has been set.
func (o *CreatePaymentMethodRequestIntegrationMetadata) GetStripeMetadataOk() (*CreatePaymentMethodRequestIntegrationMetadataStripeMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StripeMetadata, true
}

// SetStripeMetadata sets field value
func (o *CreatePaymentMethodRequestIntegrationMetadata) SetStripeMetadata(v CreatePaymentMethodRequestIntegrationMetadataStripeMetadata) {
	o.StripeMetadata = v
}

func (o CreatePaymentMethodRequestIntegrationMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["integration_id"] = o.IntegrationId
	}
	if true {
		toSerialize["stripe_metadata"] = o.StripeMetadata
	}
	return json.Marshal(toSerialize)
}

type NullableCreatePaymentMethodRequestIntegrationMetadata struct {
	value *CreatePaymentMethodRequestIntegrationMetadata
	isSet bool
}

func (v NullableCreatePaymentMethodRequestIntegrationMetadata) Get() *CreatePaymentMethodRequestIntegrationMetadata {
	return v.value
}

func (v *NullableCreatePaymentMethodRequestIntegrationMetadata) Set(val *CreatePaymentMethodRequestIntegrationMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePaymentMethodRequestIntegrationMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePaymentMethodRequestIntegrationMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePaymentMethodRequestIntegrationMetadata(val *CreatePaymentMethodRequestIntegrationMetadata) *NullableCreatePaymentMethodRequestIntegrationMetadata {
	return &NullableCreatePaymentMethodRequestIntegrationMetadata{value: val, isSet: true}
}

func (v NullableCreatePaymentMethodRequestIntegrationMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePaymentMethodRequestIntegrationMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
