/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// checks if the RecipientAccountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecipientAccountResponse{}

// RecipientAccountResponse struct for RecipientAccountResponse
type RecipientAccountResponse struct {
	// A unique identifier generated after creating recipient
	RecipientAccountId *string `json:"recipient_account_id,omitempty"`
	// Accountholder name of the recipient's account
	AccountholderName *string                 `json:"accountholder_name,omitempty"`
	AccountNumber     *RecipientAccountNumber `json:"account_number,omitempty"`
	// Type of recipient account.
	AccountType *string `json:"account_type,omitempty"`
	// List of currencies supported by the recipient account
	Currencies []string `json:"currencies,omitempty"`
	// Finverse Institution ID for the recipient’s institution.
	InstitutionId *string `json:"institution_id,omitempty"`
	// Institution Name for the sender’s institution.
	InstitutionName *string `json:"institution_name,omitempty"`
	// 3-digit code associated with bank
	BankCode *string `json:"bank_code,omitempty"`
	// 3-digit code used to identify specific bank branch
	BranchCode           *string `json:"branch_code,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RecipientAccountResponse RecipientAccountResponse

// NewRecipientAccountResponse instantiates a new RecipientAccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecipientAccountResponse() *RecipientAccountResponse {
	this := RecipientAccountResponse{}
	return &this
}

// NewRecipientAccountResponseWithDefaults instantiates a new RecipientAccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecipientAccountResponseWithDefaults() *RecipientAccountResponse {
	this := RecipientAccountResponse{}
	return &this
}

// GetRecipientAccountId returns the RecipientAccountId field value if set, zero value otherwise.
func (o *RecipientAccountResponse) GetRecipientAccountId() string {
	if o == nil || IsNil(o.RecipientAccountId) {
		var ret string
		return ret
	}
	return *o.RecipientAccountId
}

// GetRecipientAccountIdOk returns a tuple with the RecipientAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientAccountResponse) GetRecipientAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.RecipientAccountId) {
		return nil, false
	}
	return o.RecipientAccountId, true
}

// HasRecipientAccountId returns a boolean if a field has been set.
func (o *RecipientAccountResponse) HasRecipientAccountId() bool {
	if o != nil && !IsNil(o.RecipientAccountId) {
		return true
	}

	return false
}

// SetRecipientAccountId gets a reference to the given string and assigns it to the RecipientAccountId field.
func (o *RecipientAccountResponse) SetRecipientAccountId(v string) {
	o.RecipientAccountId = &v
}

// GetAccountholderName returns the AccountholderName field value if set, zero value otherwise.
func (o *RecipientAccountResponse) GetAccountholderName() string {
	if o == nil || IsNil(o.AccountholderName) {
		var ret string
		return ret
	}
	return *o.AccountholderName
}

// GetAccountholderNameOk returns a tuple with the AccountholderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientAccountResponse) GetAccountholderNameOk() (*string, bool) {
	if o == nil || IsNil(o.AccountholderName) {
		return nil, false
	}
	return o.AccountholderName, true
}

// HasAccountholderName returns a boolean if a field has been set.
func (o *RecipientAccountResponse) HasAccountholderName() bool {
	if o != nil && !IsNil(o.AccountholderName) {
		return true
	}

	return false
}

// SetAccountholderName gets a reference to the given string and assigns it to the AccountholderName field.
func (o *RecipientAccountResponse) SetAccountholderName(v string) {
	o.AccountholderName = &v
}

// GetAccountNumber returns the AccountNumber field value if set, zero value otherwise.
func (o *RecipientAccountResponse) GetAccountNumber() RecipientAccountNumber {
	if o == nil || IsNil(o.AccountNumber) {
		var ret RecipientAccountNumber
		return ret
	}
	return *o.AccountNumber
}

// GetAccountNumberOk returns a tuple with the AccountNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientAccountResponse) GetAccountNumberOk() (*RecipientAccountNumber, bool) {
	if o == nil || IsNil(o.AccountNumber) {
		return nil, false
	}
	return o.AccountNumber, true
}

// HasAccountNumber returns a boolean if a field has been set.
func (o *RecipientAccountResponse) HasAccountNumber() bool {
	if o != nil && !IsNil(o.AccountNumber) {
		return true
	}

	return false
}

// SetAccountNumber gets a reference to the given RecipientAccountNumber and assigns it to the AccountNumber field.
func (o *RecipientAccountResponse) SetAccountNumber(v RecipientAccountNumber) {
	o.AccountNumber = &v
}

// GetAccountType returns the AccountType field value if set, zero value otherwise.
func (o *RecipientAccountResponse) GetAccountType() string {
	if o == nil || IsNil(o.AccountType) {
		var ret string
		return ret
	}
	return *o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientAccountResponse) GetAccountTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AccountType) {
		return nil, false
	}
	return o.AccountType, true
}

// HasAccountType returns a boolean if a field has been set.
func (o *RecipientAccountResponse) HasAccountType() bool {
	if o != nil && !IsNil(o.AccountType) {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given string and assigns it to the AccountType field.
func (o *RecipientAccountResponse) SetAccountType(v string) {
	o.AccountType = &v
}

// GetCurrencies returns the Currencies field value if set, zero value otherwise.
func (o *RecipientAccountResponse) GetCurrencies() []string {
	if o == nil || IsNil(o.Currencies) {
		var ret []string
		return ret
	}
	return o.Currencies
}

// GetCurrenciesOk returns a tuple with the Currencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientAccountResponse) GetCurrenciesOk() ([]string, bool) {
	if o == nil || IsNil(o.Currencies) {
		return nil, false
	}
	return o.Currencies, true
}

// HasCurrencies returns a boolean if a field has been set.
func (o *RecipientAccountResponse) HasCurrencies() bool {
	if o != nil && !IsNil(o.Currencies) {
		return true
	}

	return false
}

// SetCurrencies gets a reference to the given []string and assigns it to the Currencies field.
func (o *RecipientAccountResponse) SetCurrencies(v []string) {
	o.Currencies = v
}

// GetInstitutionId returns the InstitutionId field value if set, zero value otherwise.
func (o *RecipientAccountResponse) GetInstitutionId() string {
	if o == nil || IsNil(o.InstitutionId) {
		var ret string
		return ret
	}
	return *o.InstitutionId
}

// GetInstitutionIdOk returns a tuple with the InstitutionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientAccountResponse) GetInstitutionIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstitutionId) {
		return nil, false
	}
	return o.InstitutionId, true
}

// HasInstitutionId returns a boolean if a field has been set.
func (o *RecipientAccountResponse) HasInstitutionId() bool {
	if o != nil && !IsNil(o.InstitutionId) {
		return true
	}

	return false
}

// SetInstitutionId gets a reference to the given string and assigns it to the InstitutionId field.
func (o *RecipientAccountResponse) SetInstitutionId(v string) {
	o.InstitutionId = &v
}

// GetInstitutionName returns the InstitutionName field value if set, zero value otherwise.
func (o *RecipientAccountResponse) GetInstitutionName() string {
	if o == nil || IsNil(o.InstitutionName) {
		var ret string
		return ret
	}
	return *o.InstitutionName
}

// GetInstitutionNameOk returns a tuple with the InstitutionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientAccountResponse) GetInstitutionNameOk() (*string, bool) {
	if o == nil || IsNil(o.InstitutionName) {
		return nil, false
	}
	return o.InstitutionName, true
}

// HasInstitutionName returns a boolean if a field has been set.
func (o *RecipientAccountResponse) HasInstitutionName() bool {
	if o != nil && !IsNil(o.InstitutionName) {
		return true
	}

	return false
}

// SetInstitutionName gets a reference to the given string and assigns it to the InstitutionName field.
func (o *RecipientAccountResponse) SetInstitutionName(v string) {
	o.InstitutionName = &v
}

// GetBankCode returns the BankCode field value if set, zero value otherwise.
func (o *RecipientAccountResponse) GetBankCode() string {
	if o == nil || IsNil(o.BankCode) {
		var ret string
		return ret
	}
	return *o.BankCode
}

// GetBankCodeOk returns a tuple with the BankCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientAccountResponse) GetBankCodeOk() (*string, bool) {
	if o == nil || IsNil(o.BankCode) {
		return nil, false
	}
	return o.BankCode, true
}

// HasBankCode returns a boolean if a field has been set.
func (o *RecipientAccountResponse) HasBankCode() bool {
	if o != nil && !IsNil(o.BankCode) {
		return true
	}

	return false
}

// SetBankCode gets a reference to the given string and assigns it to the BankCode field.
func (o *RecipientAccountResponse) SetBankCode(v string) {
	o.BankCode = &v
}

// GetBranchCode returns the BranchCode field value if set, zero value otherwise.
func (o *RecipientAccountResponse) GetBranchCode() string {
	if o == nil || IsNil(o.BranchCode) {
		var ret string
		return ret
	}
	return *o.BranchCode
}

// GetBranchCodeOk returns a tuple with the BranchCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientAccountResponse) GetBranchCodeOk() (*string, bool) {
	if o == nil || IsNil(o.BranchCode) {
		return nil, false
	}
	return o.BranchCode, true
}

// HasBranchCode returns a boolean if a field has been set.
func (o *RecipientAccountResponse) HasBranchCode() bool {
	if o != nil && !IsNil(o.BranchCode) {
		return true
	}

	return false
}

// SetBranchCode gets a reference to the given string and assigns it to the BranchCode field.
func (o *RecipientAccountResponse) SetBranchCode(v string) {
	o.BranchCode = &v
}

func (o RecipientAccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecipientAccountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RecipientAccountId) {
		toSerialize["recipient_account_id"] = o.RecipientAccountId
	}
	if !IsNil(o.AccountholderName) {
		toSerialize["accountholder_name"] = o.AccountholderName
	}
	if !IsNil(o.AccountNumber) {
		toSerialize["account_number"] = o.AccountNumber
	}
	if !IsNil(o.AccountType) {
		toSerialize["account_type"] = o.AccountType
	}
	if !IsNil(o.Currencies) {
		toSerialize["currencies"] = o.Currencies
	}
	if !IsNil(o.InstitutionId) {
		toSerialize["institution_id"] = o.InstitutionId
	}
	if !IsNil(o.InstitutionName) {
		toSerialize["institution_name"] = o.InstitutionName
	}
	if !IsNil(o.BankCode) {
		toSerialize["bank_code"] = o.BankCode
	}
	if !IsNil(o.BranchCode) {
		toSerialize["branch_code"] = o.BranchCode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RecipientAccountResponse) UnmarshalJSON(data []byte) (err error) {
	varRecipientAccountResponse := _RecipientAccountResponse{}

	err = json.Unmarshal(data, &varRecipientAccountResponse)

	if err != nil {
		return err
	}

	*o = RecipientAccountResponse(varRecipientAccountResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "recipient_account_id")
		delete(additionalProperties, "accountholder_name")
		delete(additionalProperties, "account_number")
		delete(additionalProperties, "account_type")
		delete(additionalProperties, "currencies")
		delete(additionalProperties, "institution_id")
		delete(additionalProperties, "institution_name")
		delete(additionalProperties, "bank_code")
		delete(additionalProperties, "branch_code")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRecipientAccountResponse struct {
	value *RecipientAccountResponse
	isSet bool
}

func (v NullableRecipientAccountResponse) Get() *RecipientAccountResponse {
	return v.value
}

func (v *NullableRecipientAccountResponse) Set(val *RecipientAccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRecipientAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRecipientAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecipientAccountResponse(val *RecipientAccountResponse) *NullableRecipientAccountResponse {
	return &NullableRecipientAccountResponse{value: val, isSet: true}
}

func (v NullableRecipientAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecipientAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
