/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: devs@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// IncomeEstimate struct for IncomeEstimate
type IncomeEstimate struct {
	// Income amount
	Amount *float32 `json:"amount,omitempty"`
	// Currency
	Currency *string `json:"currency,omitempty"`
}

// NewIncomeEstimate instantiates a new IncomeEstimate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncomeEstimate() *IncomeEstimate {
	this := IncomeEstimate{}
	return &this
}

// NewIncomeEstimateWithDefaults instantiates a new IncomeEstimate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncomeEstimateWithDefaults() *IncomeEstimate {
	this := IncomeEstimate{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *IncomeEstimate) GetAmount() float32 {
	if o == nil || o.Amount == nil {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomeEstimate) GetAmountOk() (*float32, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *IncomeEstimate) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *IncomeEstimate) SetAmount(v float32) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *IncomeEstimate) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncomeEstimate) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *IncomeEstimate) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *IncomeEstimate) SetCurrency(v string) {
	o.Currency = &v
}

func (o IncomeEstimate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	return json.Marshal(toSerialize)
}

type NullableIncomeEstimate struct {
	value *IncomeEstimate
	isSet bool
}

func (v NullableIncomeEstimate) Get() *IncomeEstimate {
	return v.value
}

func (v *NullableIncomeEstimate) Set(val *IncomeEstimate) {
	v.value = val
	v.isSet = true
}

func (v NullableIncomeEstimate) IsSet() bool {
	return v.isSet
}

func (v *NullableIncomeEstimate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncomeEstimate(val *IncomeEstimate) *NullableIncomeEstimate {
	return &NullableIncomeEstimate{value: val, isSet: true}
}

func (v NullableIncomeEstimate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncomeEstimate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
