/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
)

// checks if the RiskData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskData{}

// RiskData struct for RiskData
type RiskData struct {
	// The browser type
	BrowserType *string `json:"browser_type,omitempty"`
	// The device type
	DeviceType *string `json:"device_type,omitempty"`
	// The shopper country
	ShopperCountry *string `json:"shopper_country,omitempty"`
	// The shopper IP address
	ShopperIp *string `json:"shopper_ip,omitempty"`
	// The shopper locale
	ShopperLocale        *string `json:"shopper_locale,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RiskData RiskData

// NewRiskData instantiates a new RiskData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskData() *RiskData {
	this := RiskData{}
	return &this
}

// NewRiskDataWithDefaults instantiates a new RiskData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskDataWithDefaults() *RiskData {
	this := RiskData{}
	return &this
}

// GetBrowserType returns the BrowserType field value if set, zero value otherwise.
func (o *RiskData) GetBrowserType() string {
	if o == nil || IsNil(o.BrowserType) {
		var ret string
		return ret
	}
	return *o.BrowserType
}

// GetBrowserTypeOk returns a tuple with the BrowserType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskData) GetBrowserTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BrowserType) {
		return nil, false
	}
	return o.BrowserType, true
}

// HasBrowserType returns a boolean if a field has been set.
func (o *RiskData) HasBrowserType() bool {
	if o != nil && !IsNil(o.BrowserType) {
		return true
	}

	return false
}

// SetBrowserType gets a reference to the given string and assigns it to the BrowserType field.
func (o *RiskData) SetBrowserType(v string) {
	o.BrowserType = &v
}

// GetDeviceType returns the DeviceType field value if set, zero value otherwise.
func (o *RiskData) GetDeviceType() string {
	if o == nil || IsNil(o.DeviceType) {
		var ret string
		return ret
	}
	return *o.DeviceType
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskData) GetDeviceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceType) {
		return nil, false
	}
	return o.DeviceType, true
}

// HasDeviceType returns a boolean if a field has been set.
func (o *RiskData) HasDeviceType() bool {
	if o != nil && !IsNil(o.DeviceType) {
		return true
	}

	return false
}

// SetDeviceType gets a reference to the given string and assigns it to the DeviceType field.
func (o *RiskData) SetDeviceType(v string) {
	o.DeviceType = &v
}

// GetShopperCountry returns the ShopperCountry field value if set, zero value otherwise.
func (o *RiskData) GetShopperCountry() string {
	if o == nil || IsNil(o.ShopperCountry) {
		var ret string
		return ret
	}
	return *o.ShopperCountry
}

// GetShopperCountryOk returns a tuple with the ShopperCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskData) GetShopperCountryOk() (*string, bool) {
	if o == nil || IsNil(o.ShopperCountry) {
		return nil, false
	}
	return o.ShopperCountry, true
}

// HasShopperCountry returns a boolean if a field has been set.
func (o *RiskData) HasShopperCountry() bool {
	if o != nil && !IsNil(o.ShopperCountry) {
		return true
	}

	return false
}

// SetShopperCountry gets a reference to the given string and assigns it to the ShopperCountry field.
func (o *RiskData) SetShopperCountry(v string) {
	o.ShopperCountry = &v
}

// GetShopperIp returns the ShopperIp field value if set, zero value otherwise.
func (o *RiskData) GetShopperIp() string {
	if o == nil || IsNil(o.ShopperIp) {
		var ret string
		return ret
	}
	return *o.ShopperIp
}

// GetShopperIpOk returns a tuple with the ShopperIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskData) GetShopperIpOk() (*string, bool) {
	if o == nil || IsNil(o.ShopperIp) {
		return nil, false
	}
	return o.ShopperIp, true
}

// HasShopperIp returns a boolean if a field has been set.
func (o *RiskData) HasShopperIp() bool {
	if o != nil && !IsNil(o.ShopperIp) {
		return true
	}

	return false
}

// SetShopperIp gets a reference to the given string and assigns it to the ShopperIp field.
func (o *RiskData) SetShopperIp(v string) {
	o.ShopperIp = &v
}

// GetShopperLocale returns the ShopperLocale field value if set, zero value otherwise.
func (o *RiskData) GetShopperLocale() string {
	if o == nil || IsNil(o.ShopperLocale) {
		var ret string
		return ret
	}
	return *o.ShopperLocale
}

// GetShopperLocaleOk returns a tuple with the ShopperLocale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskData) GetShopperLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.ShopperLocale) {
		return nil, false
	}
	return o.ShopperLocale, true
}

// HasShopperLocale returns a boolean if a field has been set.
func (o *RiskData) HasShopperLocale() bool {
	if o != nil && !IsNil(o.ShopperLocale) {
		return true
	}

	return false
}

// SetShopperLocale gets a reference to the given string and assigns it to the ShopperLocale field.
func (o *RiskData) SetShopperLocale(v string) {
	o.ShopperLocale = &v
}

func (o RiskData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BrowserType) {
		toSerialize["browser_type"] = o.BrowserType
	}
	if !IsNil(o.DeviceType) {
		toSerialize["device_type"] = o.DeviceType
	}
	if !IsNil(o.ShopperCountry) {
		toSerialize["shopper_country"] = o.ShopperCountry
	}
	if !IsNil(o.ShopperIp) {
		toSerialize["shopper_ip"] = o.ShopperIp
	}
	if !IsNil(o.ShopperLocale) {
		toSerialize["shopper_locale"] = o.ShopperLocale
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RiskData) UnmarshalJSON(data []byte) (err error) {
	varRiskData := _RiskData{}

	err = json.Unmarshal(data, &varRiskData)

	if err != nil {
		return err
	}

	*o = RiskData(varRiskData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "browser_type")
		delete(additionalProperties, "device_type")
		delete(additionalProperties, "shopper_country")
		delete(additionalProperties, "shopper_ip")
		delete(additionalProperties, "shopper_locale")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRiskData struct {
	value *RiskData
	isSet bool
}

func (v NullableRiskData) Get() *RiskData {
	return v.value
}

func (v *NullableRiskData) Set(val *RiskData) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskData) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskData(val *RiskData) *NullableRiskData {
	return &NullableRiskData{value: val, isSet: true}
}

func (v NullableRiskData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
