/*
Finverse Public

Documentation of the early finverse services

API version: 0.0.1
Contact: info@finverse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finverse

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the PaymentLinkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentLinkResponse{}

// PaymentLinkResponse struct for PaymentLinkResponse
type PaymentLinkResponse struct {
	// Finverse Payment Link ID
	PaymentLinkId string `json:"payment_link_id"`
	// The amount of the payment. Expressed in currency's smallest unit or “minor unit”, as defined in ISO 4217.
	Amount             int32                      `json:"amount"`
	Currency           string                     `json:"currency"`
	LinkCustomizations *PaymentLinkCustomizations `json:"link_customizations,omitempty"`
	Mode               PaymentLinkMode            `json:"mode"`
	PaymentDetails     *PaymentLinkDetails        `json:"payment_details,omitempty"`
	// Unique reference id to identifying the payment to be collected.
	UniqueReferenceId   *string              `json:"unique_reference_id,omitempty"`
	PaymentSetupOptions *PaymentSetupOptions `json:"payment_setup_options,omitempty"`
	// Additional attributes of the payment link in key:value format (e.g. payment_id: 1234). It supports up to 20 key:value pairs, whereas the key and value supports up to 50 and 1000 characters respectively.
	Metadata *map[string]string `json:"metadata,omitempty"`
	// Key-Value metadata to store on payments created on this Payment Link
	PaymentMetadata *map[string]string `json:"payment_metadata,omitempty"`
	// The URL for payment link
	Url           *string                  `json:"url,omitempty"`
	Status        PaymentLinkStatus        `json:"status"`
	SessionStatus PaymentLinkSessionStatus `json:"session_status"`
	// Timestamp of when the payment link was created in ISO format (YYYY-MM-DDTHH:MM:SS.SSSZ)
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Timestamp of when the payment link was last updated in ISO format (YYYY-MM-DDTHH:MM:SS.SSSZ)
	UpdatedAt            *time.Time                   `json:"updated_at,omitempty"`
	Payment              *PaymentResponse             `json:"payment,omitempty"`
	Sender               *PaymentLinkSenderResponse   `json:"sender,omitempty"`
	PaymentMethod        *PaymentMethodResponse       `json:"payment_method,omitempty"`
	IntegrationMetadata  *IntegrationMetadataResponse `json:"integration_metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaymentLinkResponse PaymentLinkResponse

// NewPaymentLinkResponse instantiates a new PaymentLinkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentLinkResponse(paymentLinkId string, amount int32, currency string, mode PaymentLinkMode, status PaymentLinkStatus, sessionStatus PaymentLinkSessionStatus) *PaymentLinkResponse {
	this := PaymentLinkResponse{}
	this.PaymentLinkId = paymentLinkId
	this.Amount = amount
	this.Currency = currency
	this.Mode = mode
	this.Status = status
	this.SessionStatus = sessionStatus
	return &this
}

// NewPaymentLinkResponseWithDefaults instantiates a new PaymentLinkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentLinkResponseWithDefaults() *PaymentLinkResponse {
	this := PaymentLinkResponse{}
	return &this
}

// GetPaymentLinkId returns the PaymentLinkId field value
func (o *PaymentLinkResponse) GetPaymentLinkId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentLinkId
}

// GetPaymentLinkIdOk returns a tuple with the PaymentLinkId field value
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetPaymentLinkIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentLinkId, true
}

// SetPaymentLinkId sets field value
func (o *PaymentLinkResponse) SetPaymentLinkId(v string) {
	o.PaymentLinkId = v
}

// GetAmount returns the Amount field value
func (o *PaymentLinkResponse) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PaymentLinkResponse) SetAmount(v int32) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *PaymentLinkResponse) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PaymentLinkResponse) SetCurrency(v string) {
	o.Currency = v
}

// GetLinkCustomizations returns the LinkCustomizations field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetLinkCustomizations() PaymentLinkCustomizations {
	if o == nil || IsNil(o.LinkCustomizations) {
		var ret PaymentLinkCustomizations
		return ret
	}
	return *o.LinkCustomizations
}

// GetLinkCustomizationsOk returns a tuple with the LinkCustomizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetLinkCustomizationsOk() (*PaymentLinkCustomizations, bool) {
	if o == nil || IsNil(o.LinkCustomizations) {
		return nil, false
	}
	return o.LinkCustomizations, true
}

// HasLinkCustomizations returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasLinkCustomizations() bool {
	if o != nil && !IsNil(o.LinkCustomizations) {
		return true
	}

	return false
}

// SetLinkCustomizations gets a reference to the given PaymentLinkCustomizations and assigns it to the LinkCustomizations field.
func (o *PaymentLinkResponse) SetLinkCustomizations(v PaymentLinkCustomizations) {
	o.LinkCustomizations = &v
}

// GetMode returns the Mode field value
func (o *PaymentLinkResponse) GetMode() PaymentLinkMode {
	if o == nil {
		var ret PaymentLinkMode
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetModeOk() (*PaymentLinkMode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *PaymentLinkResponse) SetMode(v PaymentLinkMode) {
	o.Mode = v
}

// GetPaymentDetails returns the PaymentDetails field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetPaymentDetails() PaymentLinkDetails {
	if o == nil || IsNil(o.PaymentDetails) {
		var ret PaymentLinkDetails
		return ret
	}
	return *o.PaymentDetails
}

// GetPaymentDetailsOk returns a tuple with the PaymentDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetPaymentDetailsOk() (*PaymentLinkDetails, bool) {
	if o == nil || IsNil(o.PaymentDetails) {
		return nil, false
	}
	return o.PaymentDetails, true
}

// HasPaymentDetails returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasPaymentDetails() bool {
	if o != nil && !IsNil(o.PaymentDetails) {
		return true
	}

	return false
}

// SetPaymentDetails gets a reference to the given PaymentLinkDetails and assigns it to the PaymentDetails field.
func (o *PaymentLinkResponse) SetPaymentDetails(v PaymentLinkDetails) {
	o.PaymentDetails = &v
}

// GetUniqueReferenceId returns the UniqueReferenceId field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetUniqueReferenceId() string {
	if o == nil || IsNil(o.UniqueReferenceId) {
		var ret string
		return ret
	}
	return *o.UniqueReferenceId
}

// GetUniqueReferenceIdOk returns a tuple with the UniqueReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetUniqueReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.UniqueReferenceId) {
		return nil, false
	}
	return o.UniqueReferenceId, true
}

// HasUniqueReferenceId returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasUniqueReferenceId() bool {
	if o != nil && !IsNil(o.UniqueReferenceId) {
		return true
	}

	return false
}

// SetUniqueReferenceId gets a reference to the given string and assigns it to the UniqueReferenceId field.
func (o *PaymentLinkResponse) SetUniqueReferenceId(v string) {
	o.UniqueReferenceId = &v
}

// GetPaymentSetupOptions returns the PaymentSetupOptions field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetPaymentSetupOptions() PaymentSetupOptions {
	if o == nil || IsNil(o.PaymentSetupOptions) {
		var ret PaymentSetupOptions
		return ret
	}
	return *o.PaymentSetupOptions
}

// GetPaymentSetupOptionsOk returns a tuple with the PaymentSetupOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetPaymentSetupOptionsOk() (*PaymentSetupOptions, bool) {
	if o == nil || IsNil(o.PaymentSetupOptions) {
		return nil, false
	}
	return o.PaymentSetupOptions, true
}

// HasPaymentSetupOptions returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasPaymentSetupOptions() bool {
	if o != nil && !IsNil(o.PaymentSetupOptions) {
		return true
	}

	return false
}

// SetPaymentSetupOptions gets a reference to the given PaymentSetupOptions and assigns it to the PaymentSetupOptions field.
func (o *PaymentLinkResponse) SetPaymentSetupOptions(v PaymentSetupOptions) {
	o.PaymentSetupOptions = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *PaymentLinkResponse) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetPaymentMetadata returns the PaymentMetadata field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetPaymentMetadata() map[string]string {
	if o == nil || IsNil(o.PaymentMetadata) {
		var ret map[string]string
		return ret
	}
	return *o.PaymentMetadata
}

// GetPaymentMetadataOk returns a tuple with the PaymentMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetPaymentMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PaymentMetadata) {
		return nil, false
	}
	return o.PaymentMetadata, true
}

// HasPaymentMetadata returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasPaymentMetadata() bool {
	if o != nil && !IsNil(o.PaymentMetadata) {
		return true
	}

	return false
}

// SetPaymentMetadata gets a reference to the given map[string]string and assigns it to the PaymentMetadata field.
func (o *PaymentLinkResponse) SetPaymentMetadata(v map[string]string) {
	o.PaymentMetadata = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *PaymentLinkResponse) SetUrl(v string) {
	o.Url = &v
}

// GetStatus returns the Status field value
func (o *PaymentLinkResponse) GetStatus() PaymentLinkStatus {
	if o == nil {
		var ret PaymentLinkStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetStatusOk() (*PaymentLinkStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PaymentLinkResponse) SetStatus(v PaymentLinkStatus) {
	o.Status = v
}

// GetSessionStatus returns the SessionStatus field value
func (o *PaymentLinkResponse) GetSessionStatus() PaymentLinkSessionStatus {
	if o == nil {
		var ret PaymentLinkSessionStatus
		return ret
	}

	return o.SessionStatus
}

// GetSessionStatusOk returns a tuple with the SessionStatus field value
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetSessionStatusOk() (*PaymentLinkSessionStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionStatus, true
}

// SetSessionStatus sets field value
func (o *PaymentLinkResponse) SetSessionStatus(v PaymentLinkSessionStatus) {
	o.SessionStatus = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *PaymentLinkResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *PaymentLinkResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetPayment returns the Payment field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetPayment() PaymentResponse {
	if o == nil || IsNil(o.Payment) {
		var ret PaymentResponse
		return ret
	}
	return *o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetPaymentOk() (*PaymentResponse, bool) {
	if o == nil || IsNil(o.Payment) {
		return nil, false
	}
	return o.Payment, true
}

// HasPayment returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasPayment() bool {
	if o != nil && !IsNil(o.Payment) {
		return true
	}

	return false
}

// SetPayment gets a reference to the given PaymentResponse and assigns it to the Payment field.
func (o *PaymentLinkResponse) SetPayment(v PaymentResponse) {
	o.Payment = &v
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetSender() PaymentLinkSenderResponse {
	if o == nil || IsNil(o.Sender) {
		var ret PaymentLinkSenderResponse
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetSenderOk() (*PaymentLinkSenderResponse, bool) {
	if o == nil || IsNil(o.Sender) {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasSender() bool {
	if o != nil && !IsNil(o.Sender) {
		return true
	}

	return false
}

// SetSender gets a reference to the given PaymentLinkSenderResponse and assigns it to the Sender field.
func (o *PaymentLinkResponse) SetSender(v PaymentLinkSenderResponse) {
	o.Sender = &v
}

// GetPaymentMethod returns the PaymentMethod field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetPaymentMethod() PaymentMethodResponse {
	if o == nil || IsNil(o.PaymentMethod) {
		var ret PaymentMethodResponse
		return ret
	}
	return *o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetPaymentMethodOk() (*PaymentMethodResponse, bool) {
	if o == nil || IsNil(o.PaymentMethod) {
		return nil, false
	}
	return o.PaymentMethod, true
}

// HasPaymentMethod returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasPaymentMethod() bool {
	if o != nil && !IsNil(o.PaymentMethod) {
		return true
	}

	return false
}

// SetPaymentMethod gets a reference to the given PaymentMethodResponse and assigns it to the PaymentMethod field.
func (o *PaymentLinkResponse) SetPaymentMethod(v PaymentMethodResponse) {
	o.PaymentMethod = &v
}

// GetIntegrationMetadata returns the IntegrationMetadata field value if set, zero value otherwise.
func (o *PaymentLinkResponse) GetIntegrationMetadata() IntegrationMetadataResponse {
	if o == nil || IsNil(o.IntegrationMetadata) {
		var ret IntegrationMetadataResponse
		return ret
	}
	return *o.IntegrationMetadata
}

// GetIntegrationMetadataOk returns a tuple with the IntegrationMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentLinkResponse) GetIntegrationMetadataOk() (*IntegrationMetadataResponse, bool) {
	if o == nil || IsNil(o.IntegrationMetadata) {
		return nil, false
	}
	return o.IntegrationMetadata, true
}

// HasIntegrationMetadata returns a boolean if a field has been set.
func (o *PaymentLinkResponse) HasIntegrationMetadata() bool {
	if o != nil && !IsNil(o.IntegrationMetadata) {
		return true
	}

	return false
}

// SetIntegrationMetadata gets a reference to the given IntegrationMetadataResponse and assigns it to the IntegrationMetadata field.
func (o *PaymentLinkResponse) SetIntegrationMetadata(v IntegrationMetadataResponse) {
	o.IntegrationMetadata = &v
}

func (o PaymentLinkResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentLinkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["payment_link_id"] = o.PaymentLinkId
	toSerialize["amount"] = o.Amount
	toSerialize["currency"] = o.Currency
	if !IsNil(o.LinkCustomizations) {
		toSerialize["link_customizations"] = o.LinkCustomizations
	}
	toSerialize["mode"] = o.Mode
	if !IsNil(o.PaymentDetails) {
		toSerialize["payment_details"] = o.PaymentDetails
	}
	if !IsNil(o.UniqueReferenceId) {
		toSerialize["unique_reference_id"] = o.UniqueReferenceId
	}
	if !IsNil(o.PaymentSetupOptions) {
		toSerialize["payment_setup_options"] = o.PaymentSetupOptions
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.PaymentMetadata) {
		toSerialize["payment_metadata"] = o.PaymentMetadata
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	toSerialize["status"] = o.Status
	toSerialize["session_status"] = o.SessionStatus
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Payment) {
		toSerialize["payment"] = o.Payment
	}
	if !IsNil(o.Sender) {
		toSerialize["sender"] = o.Sender
	}
	if !IsNil(o.PaymentMethod) {
		toSerialize["payment_method"] = o.PaymentMethod
	}
	if !IsNil(o.IntegrationMetadata) {
		toSerialize["integration_metadata"] = o.IntegrationMetadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentLinkResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"payment_link_id",
		"amount",
		"currency",
		"mode",
		"status",
		"session_status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentLinkResponse := _PaymentLinkResponse{}

	err = json.Unmarshal(data, &varPaymentLinkResponse)

	if err != nil {
		return err
	}

	*o = PaymentLinkResponse(varPaymentLinkResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "payment_link_id")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "link_customizations")
		delete(additionalProperties, "mode")
		delete(additionalProperties, "payment_details")
		delete(additionalProperties, "unique_reference_id")
		delete(additionalProperties, "payment_setup_options")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "payment_metadata")
		delete(additionalProperties, "url")
		delete(additionalProperties, "status")
		delete(additionalProperties, "session_status")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "payment")
		delete(additionalProperties, "sender")
		delete(additionalProperties, "payment_method")
		delete(additionalProperties, "integration_metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaymentLinkResponse struct {
	value *PaymentLinkResponse
	isSet bool
}

func (v NullablePaymentLinkResponse) Get() *PaymentLinkResponse {
	return v.value
}

func (v *NullablePaymentLinkResponse) Set(val *PaymentLinkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentLinkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentLinkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentLinkResponse(val *PaymentLinkResponse) *NullablePaymentLinkResponse {
	return &NullablePaymentLinkResponse{value: val, isSet: true}
}

func (v NullablePaymentLinkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentLinkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
